Repository qor5/admin, pull requests merged in 2022-12, with the labels that each got.

#7 Fix publish url display
  pagebuilder/builder.go
Labels: size/S

#6 More containers
  pagebuilder/example/assets/images/ListContentLite.png
  pagebuilder/example/assets/images/ListContentWithImage.png
  pagebuilder/example/assets/images/PageTitle.png
  pagebuilder/example/config.go
  pagebuilder/example/containers/list_content_lite.go
  pagebuilder/example/containers/list_content_with_image.go
  pagebuilder/example/containers/page_title.go
  pagebuilder/example/containers/tag.go
Labels: size/L

#5 nested field
  example/admin/customer_config.go
  example/admin/db.go
  example/models/address.go
  example/pages/list_editor_example.go
  listeditor/builder.go
  listeditor/config.go
  listeditor/sort.go
  pagebuilder/example/containers/brand_grid.go
  pagebuilder/example/containers/in_numbers.go
  pagebuilder/example/containers/list_content.go
  presets/actions/const.go
  presets/const.go
  presets/field.go
  presets/integration/fields_test.go
  presets/listeditor.go
  presets/model.go
  role/config.go
Labels: size/XL

#9 fix example containers listeditor
  pagebuilder/example/containers/list_content_lite.go
  pagebuilder/example/containers/list_content_with_image.go
  pagebuilder/example/containers/page_title.go
  pagebuilder/example/containers/tag.go
Labels: size/S

#11 polish editing block style
  presets/field.go
  presets/listeditor.go
Labels: size/S

#12 Remove wrong referenced gorm
  presets/examples/setup.go
  presets/gorm2op/operator.go
  presets/gormop/operator.go
Labels: size/XS

#13 plantbuild: build in root dir
  hack/build-app.sh
  hack/build-deploy-app.sh
  hack/get-tools.sh
  hack/update-plantbuild.sh
  hack/verify-plantbuild.sh
  plantbuild/build.jsonnet
  plantbuild/images.jsonnet
Labels: size/S

#18 Upgrade qor5/ui to move stripeui
  go.mod
  go.sum
  presets/examples/setup.go
Labels: size/XS

#23 upgrade gorm to v1.24.2
  go.mod
  go.sum
Labels: size/XS

#24 fix fields test
  presets/integration/fields_test.go
Labels: size/XS

#25 set nil for index-out-of-range deleted item
  presets/field.go
  presets/integration/fields_test.go
Labels: size/S

#22 Field with defaults
  example/admin/user_config.go
  presets/utils.go
  presets/utils_test.go
Labels: size/M

#29 upgrade gorm to v1.24.2
  example/admin/user_config.go
  go.mod
  go.sum
  plantbuild/build.jsonnet
  plantbuild/images.jsonnet
  presets/field.go
  presets/integration/fields_test.go
  presets/utils.go
  presets/utils_test.go
Labels: size/L

#28 qor5 push to public registry
  plantbuild/build.jsonnet
  plantbuild/images.jsonnet
Labels: size/XS

#30 404 handler ignore pages that are not has admin prefix
  presets/presets.go
Labels: size/XS

#27 Fix tests
  activity/activity_model.go
  activity/activity_test.go
  activity/helper.go
  example/example_test.go
  media/integration/integration_test.go
  media/views/media_box.go
  pagebuilder/editor.go
  pagebuilder/example/containers/footer.go
  pagebuilder/example/integration_test.go
  publish/publish_test.go
  publish/test_env
  seo/helper_test.go
Labels: size/L
