Repository qor5/admin, pull requests merged in 2023-05, with the labels that each got.

#130 upgrade go to 1.20.4
  example/Dockerfile
  example/cmd/data-resetor/Dockerfile
  example/cmd/publisher/Dockerfile
Labels: size/XS

#118 fix 404 page WriteHeader
  presets/presets.go
Labels: size/XS

#104 Modify publish
  example/admin/config.go
  example/cmd/publisher/main.go
  go.mod
  go.sum
  microsite/views/config.go
  pagebuilder/publish.go
  publish/list_publish_builder.go
  publish/schedule_publish_builder.go
  publish/utils.go
Labels: size/L

#131 change test db
  activity/activity_test.go
  dev_env_test
  docker-compose.yaml
  media/integration/integration_test.go
  pagebuilder/example/integration_test.go
  presets/examples/setup.go
  presets/integration/example_test.go
  publish/publish_test.go
  seo/helper_test.go
  worker/integration_test/setup_test.go
Labels: size/M

#132 Add back button on activity log detail page
  activity/admin.go
Labels: size/XS

#133 Update go deps
  go.mod
  go.sum
  presets/integration/fields_test.go
Labels: size/L

#134 publish snippets for doc
  example/admin/data_init.go
  publish/list.go
  publish/schedule.go
  publish/status.go
  publish/version.go
Labels: size/S

#135 Fix admin root dir menu active and add test
  presets/presets.go
  presets/presets_test.go
Labels: size/M
