Repository qor5/admin, pull requests merged in 2023-01, with the labels that each got.

#33 remove list editor example page
  example/admin/config.go
Labels: size/S

#35 fix field test
  presets/integration/fields_test.go
Labels: size/S

#34 github-actions: added go build and go test
  .github/workflows/go.yml
Labels: size/M

#37 update package registry before installing libvips
  .github/workflows/go.yml
Labels: size/XS

#39 remove example url prefix patch
  example/admin/auth.go
  example/admin/config.go
  example/admin/router.go
  example/admin/user_config.go
  example/main.go
Labels: size/S

#40 fix home page mount with empty url prefix
  presets/presets.go
Labels: size/XS

#41 login view common
  go.mod
  go.sum
  login/view_common.go
  login/views.go
Labels: size/L

#17 Replace overwriting search func
  .gitignore
  activity/activity.go
  activity/helper.go
  example/admin/config.go
  example/admin/l10n_model_config.go
  example/models/category.go
  example/models/l10n_model.go
  example/models/l10n_model_with_version.go
  example/models/list_model.go
  example/models/post.go
  example/models/product.go
  gorm2op/operate.go
  l10n/interface.go
  l10n/l10n.go
  l10n/views/config.go
  l10n/views/events.go
  microsite/microsite.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/models.go
  pagebuilder/publish.go
  presets/api.go
  presets/examples/setup.go
  presets/gorm2op/operator.go
  presets/gormop/operator.go
  presets/integration/gorm_operator_test.go
  publish/interfaces.go
  publish/version.go
  publish/views/config.go
  publish/views/events.go
  publish/views/status.go
  publish/views/versions.go
  utils/get_primary_keys.go
  utils/primary_slugger_where.go
  utils/set_primary_keys.go
Labels: size/XXL

#44 fix tests
  activity/helper.go
  pagebuilder/example/integration_test.go
  presets/integration/gorm_operator_test.go
Labels: size/S

#42 fix page publish with locale
  pagebuilder/publish.go
Labels: size/XS
