Repository qor5/admin, pull requests merged in 2023-07, with the labels that each got.

#140 login: panic for unexpected errors
  go.mod
  go.sum
  login/views.go
Labels: size/S

#142 Fix sql errors in searching for non-text fields
  presets/gorm2op/operator.go
  presets/gormop/operator.go
Labels: size/S

#143 Revert "Fix sql errors in searching for non-text fields"
  example/admin/config.go
  presets/gorm2op/operator.go
  presets/gormop/operator.go
Labels: size/S

#141 optimize microsite
  example/admin/config.go
  go.mod
  go.sum
  microsite/global_variables.go
  microsite/interfaces.go
  microsite/microsite.go
  microsite/utils/archive.go
  microsite/utils/client.go
  microsite/utils/interfaces.go
  microsite/utils/utils.go
  microsite/views/config.go
Labels: size/XL

#136 Category l10n
  example/admin/data_init.go
  l10n/builder.go
  pagebuilder/builder.go
  pagebuilder/helper.go
  pagebuilder/models.go
  pagebuilder/publish.go
Labels: size/L

#58 Add default password to dev_env and disable totp by default
  example/dev_env
  pagebuilder/example/integration_test.go
Labels: size/S

#144 presets: fix singleton editing error message and change global error to VSnackbar
  go.mod
  presets/editing.go
  presets/presets.go
Labels: size/M
