Repository qor5/admin, pull requests merged in 2023-12, with the labels that each got.

#233 make media Description not only for Image
  media/views/media_box.go
Labels: size/M

#235 added DisablePagination and Title method for ListingBuilder
  presets/listing.go
Labels: size/L

#236 fix DisablePagination
  presets/listing.go
Labels: size/XS

#239 upgrade web to 1.3.2 and go to 1.21.5
  example/Dockerfile
  example/cmd/data-resetor/Dockerfile
  example/cmd/publisher/Dockerfile
  go.mod
  go.sum
Labels: size/S
