Repository qor5/admin, pull requests merged in 2023-10, with the labels that each got.

#189 Add type filter to media library
  media/views/filechooser.go
  media/views/messages.go
Labels: size/M

#190 auto localize category when localize page
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/settings.go
Labels: size/M

#191 Fix seo add variable UI
  seo/admin.go
Labels: size/S

#192 fixed cannot open pages in a new tab
  presets/presets.go
Labels: size/XS

#195 Fix version list edit icon click area
  publish/views/versions.go
Labels: size/S

#194 upgrade go version to 1.21.3
  example/Dockerfile
  example/cmd/data-resetor/Dockerfile
  example/cmd/publisher/Dockerfile
Labels: size/XS

#196 Fix pb category setter func
  pagebuilder/builder.go
Labels: size/XS

#197 Show validation err on do localize to event
  l10n/views/events.go
  presets/editing.go
Labels: size/XS

#198 Fix page localize err with empty slug
  pagebuilder/builder.go
  pagebuilder/helper.go
Labels: size/S

#199 upgrade web to 1.3.1
  go.mod
  go.sum
Labels: size/XS

#200 Fix missing actual time when updating schedule settings
  example/admin/category_config.go
  example/admin/config.go
  example/admin/product_config.go
  publish/views/config.go
Labels: size/S

#201 fix the issue where the version name does not update immediately
  presets/editing.go
Labels: size/XS

#202 Revert "fix the issue where the version name does not update immediately"
  presets/editing.go
Labels: size/XS

#203 fixed the issue where the version name dose not update immediately
  presets/editing.go
Labels: size/XS, needs-rebase

#204 upgrade x
  go.mod
  go.sum
Labels: size/XS

#205 Fix oauth user identification on example
  example/models/user.go
Labels: size/XS

#206 example: fix login empty OAuth email
  example/admin/auth.go
  go.mod
  go.sum
Labels: size/S

#209 optimize the functionality of opening in new tab
  presets/presets.go
Labels: size/S

#210 Add path to pb page listing
  pagebuilder/builder.go
  pagebuilder/helper.go
Labels: size/L

#211 fix the issue where non-admin user can see admin user info
  example/admin/user_config.go
Labels: size/XS
