Repository qor5/admin, pull requests merged in 2023-04, with the labels that each got.

#107 Polish i18n syntax in example
  example/admin/config.go
  example/admin/login_views.go
  example/admin/profile.go
  example/admin/user_config.go
Labels: size/L

#108 Format countdown time on example profile
  example/admin/config.go
Labels: size/XS

#109 Fix preload countdown format on example profile
  example/admin/config.go
Labels: size/XS

#110 fix listeditor set nil for empty slice
  presets/field.go
  presets/integration/fields_test.go
  presets/listeditor.go
Labels: size/M

#111 fix online version item
  publish/views/versions.go
Labels: size/S

#112 fix pagebuilder republish live record url
  pagebuilder/publish.go
Labels: size/XS

#102 Optimize media library
  example/cmd/data-resetor/main.go
  media/media_library/media_library.go
  media/views/filechooser.go
  media/views/list.go
  media/views/media_box.go
  media/views/messages.go
Labels: size/L

#113 Fix image preview size on media library
  media/views/filechooser.go
Labels: size/XS

#114 polish pagebuilder template selection
  pagebuilder/builder.go
  pagebuilder/messages.go
Labels: size/L

#115 Fix image extra shadow and missing video url
  media/views/filechooser.go
Labels: size/S

#116 upgrade qor5/web
  go.mod
  go.sum
Labels: size/XS

#119 fix listeditor event queries
  presets/listeditor.go
Labels: size/XS

#120 Fix pb demo container list l10n
  pagebuilder/builder.go
Labels: size/M

#121 Import initial data for example on first startup
  example/admin/config.go
  example/admin/data_init.go
  example/cmd/data-resetor/main.go
  example/dev_env
Labels: size/L

#123 l10n: fix localize to event empty to
  l10n/views/events.go
Labels: size/S

#122 Add db for go test
  .github/workflows/go.yml
Labels: size/S

#125 add login example
  login/example/main.go
Labels: size/M

#126 update login changes
  example/admin/auth.go
  example/admin/login_views.go
  example/admin/router.go
  go.mod
  go.sum
  login/builder.go
  login/example/main.go
  login/view_common.go
  login/views.go
Labels: size/L

#127 Optimize schedule publish
  example/cmd/publisher/main.go
  pagebuilder/publish.go
  publish/schedule_publish_builder.go
  publish/utils.go
Labels: size/M

#128 pass FreeStyle css/js to PageLayoutInput
  pagebuilder/editor.go
Labels: size/S
