Repository qor5/admin, pull requests merged in 2023-03, with the labels that each got.

#65 Update README
  README.md
Labels: size/S

#68 Update README.md
  README.md
Labels: size/XS

#69 add test status badge to readme
  README.md
Labels: size/XS

#76 Optimize perm rn
  presets/field.go
  presets/listing.go
  presets/model.go
  presets/presets.go
Labels: size/M

#32 Demo to public
  example/admin/assets/favicon.ico
  example/admin/assets/logo.svg
  example/admin/auth.go
  example/admin/category_config.go
  example/admin/config.go
  example/admin/customer_config.go
  example/admin/db.go
  example/admin/ec_dashboard_config.go
  example/admin/helpers.go
  example/admin/input_demo_config.go
  example/admin/job.go
  example/admin/login_views.go
  example/admin/messages.go
  example/admin/middlewares.go
  example/admin/order_config.go
  example/admin/perm.go
  example/admin/profile.go
  example/admin/router.go
  example/admin/seo.go
  example/admin/session_mgmt.go
  example/admin/user_config.go
  example/cmd/data-resetor/Dockerfile
  example/cmd/data-resetor/init_sql.go
  example/cmd/data-resetor/main.go
  example/cmd/publisher/Dockerfile
  example/dev_env
  example/models/input_demo.go
  example/models/user.go
  example/pages/list_editor_example.go
  go.mod
  go.sum
  hack/build-deploy-app.sh
  l10n/builder.go
  l10n/interface.go
  l10n/views/config.go
  l10n/views/events.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/example/examplemain/main.go
  pagebuilder/example/integration_test.go
  pagebuilder/models.go
  pagebuilder/publish.go
  plantbuild/build.jsonnet
  plantbuild/images.jsonnet
  presets/field.go
  presets/presets.go
  publish/builder.go
  publish/views/events.go
  role/config.go
  role/role.go
Labels: size/XXL

#62 Pagebuilder L10n
  example/admin/config.go
  l10n/builder.go
  l10n/interface.go
  l10n/views/config.go
  l10n/views/events.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/example/examplemain/main.go
  pagebuilder/example/integration_test.go
  pagebuilder/models.go
  pagebuilder/publish.go
  presets/field.go
  presets/presets.go
  publish/builder.go
  publish/views/events.go
Labels: size/XL, needs-rebase

#77 Update README.md
  README.md
Labels: size/XS

#73 optimize perm role
  activity/admin.go
  activity/perm_policy.go
  example/admin/config.go
  example/admin/perm.go
  go.mod
  go.sum
  pagebuilder/builder.go
  role/builder.go
  role/config.go
Labels: size/L

#79 fix sub items in no permission menu group
  presets/presets.go
Labels: size/XS

#80 Update README.md
  README.md
Labels: size/XS

#78 Polish demo to public
  example/admin/config.go
  example/admin/profile.go
  example/admin/user_config.go
  example/cmd/data-resetor/init_sql.go
  example/cmd/data-resetor/main.go
Labels: size/L

#82 Fix pagination after search
  presets/listing.go
  presets/presets.go
Labels: size/XS

#83 Update README.md
  README.md
Labels: size/XS

#86 Hide publish url when page status is not online
  pagebuilder/builder.go
Labels: size/XS

#85 Manager can only view own logs and protect demo account
  activity/activity_log.go
  activity/activity_model.go
  example/admin/config.go
  example/admin/perm.go
  example/admin/user_config.go
Labels: size/M

#88 detailing check obj permission
  example/admin/perm.go
  presets/detailing.go
Labels: size/XS

#90 demo account restrictions
  example/admin/profile.go
Labels: size/M

#92 Add support wildcard search on listing
  presets/gorm2op/operator.go
  presets/gormop/operator.go
Labels: size/S

#91 Add MIT license
  LICENSE
Labels: size/S

#93 Fix category drop box overflow on page
  pagebuilder/builder.go
Labels: size/XS

#95 fix shared container republish all pages dup records
  pagebuilder/builder.go
Labels: size/XS

#94 Optimize template
  pagebuilder/builder.go
  pagebuilder/messages.go
Labels: size/M

#97 Display oauth identifier on example user page
  example/admin/user_config.go
  example/models/user.go
Labels: size/S

#81 Demo Optimization
  example/admin/config.go
  example/admin/dashboard.go
Labels: size/S

#99 Optimize countdown on example brand area
  example/admin/config.go
Labels: size/S

#52 Click the container list to scroll and highlight the current container
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/example/containers/footer.go
  pagebuilder/example/containers/header.go
  pagebuilder/example/containers/image.go
  pagebuilder/example/integration_test.go
Labels: size/M

#61 fix heading font color
  pagebuilder/example/containers/common.go
  pagebuilder/example/containers/heading.go
Labels: size/S

#72 add preview btn in page edit form
  pagebuilder/builder.go
Labels: size/S

#101 worker activity log
  activity/activity.go
  example/admin/config.go
  worker/action_job.go
  worker/builder.go
  worker/models.go
Labels: size/L

#103 Add zh, jp lang to example profile page
  example/admin/messages.go
  example/admin/profile.go
Labels: size/L

#105 publish: fix utils message
  publish/views/status.go
Labels: size/XS
