Repository qor5/admin, pull requests merged in 2023-02, with the labels that each got.

#43 Trigger qor5-provisioning github actions
  hack/build-deploy-app.sh
  hack/get-tools.sh
Labels: size/S

#46 Trigger qor5-provisioning github actions
  hack/build-deploy-app.sh
  hack/get-tools.sh
Labels: size/S

#47 fix wrong plantbuild alias
  hack/build-deploy-app.sh
Labels: size/S

#45 Split Action and Bulk Action
  example/admin/config.go
  example/admin/helpers.go
  example/admin/order_config.go
  example/admin/product_config.go
  example/admin/router.go
  go.mod
  go.sum
  presets/action.go
  presets/api.go
  presets/bulk_action.go
  presets/const.go
  presets/detailing.go
  presets/examples/setup.go
  presets/listing.go
Labels: size/L

#51 Bucket to publish pages
  example/admin/config.go
  example/cmd/publisher/main.go
  example/dev_env
Labels: size/S

#55 Config publish bucket ACL
  example/admin/config.go
  example/cmd/publisher/main.go
Labels: size/XS

#50 listing-delete deletes all versions
  presets/listing.go
  publish/views/config.go
Labels: size/M

#53 shared containers: republish all related pages
  pagebuilder/builder.go
  pagebuilder/messages.go
  publish/views/events.go
  publish/views/status.go
Labels: size/L

#56 i18n default Japanese messages
  example/admin/config.go
  example/admin/messages.go
  go.mod
  go.sum
  l10n/views/config.go
  l10n/views/messages.go
  note/config.go
  note/messages.go
  pagebuilder/builder.go
  pagebuilder/messages.go
  presets/messages.go
  presets/presets.go
  publish/views/config.go
  publish/views/messages.go
  utils/confirm_dialog.go
  utils/messages.go
Labels: size/L

#54 Fix missing new role on user editing page
  example/admin/user_config.go
  role/config.go
Labels: size/M

#59 worker integration test
  worker/README.md
  worker/builder.go
  worker/integration_test/setup_test.go
  worker/integration_test/test_que.go
  worker/integration_test/worker_test.go
  worker/job.go
  worker/mock/qor_job.go
  worker/mock/queue.go
  worker/queue.go
Labels: size/XL

#63 Optimize publish url display
  pagebuilder/builder.go
  pagebuilder/publish.go
Labels: size/M

#64 polish confirm dialog
  pagebuilder/builder.go
  presets/messages.go
  presets/presets.go
Labels: size/M

#66 simplify confirm dialog vars
  pagebuilder/builder.go
  presets/presets.go
Labels: size/S

#67 Implement permRNer to version and l10n resource
  example/models/category.go
  example/models/l10n_model.go
  example/models/l10n_model_with_version.go
  example/models/list_model.go
  example/models/post.go
  example/models/product.go
  microsite/microsite.go
  pagebuilder/models.go
  pagebuilder/publish.go
Labels: size/M
