Repository qor5/admin, pull requests merged in 2023-08, with the labels that each got.

#146 Optimize PB category
  example/admin/data_init.go
  pagebuilder/builder.go
  pagebuilder/helper.go
  pagebuilder/models.go
Labels: size/L

#148 Fix page category
  pagebuilder/helper.go
Labels: size/XS

#151 upgrade go to 1.21.0
  example/Dockerfile
  example/cmd/data-resetor/Dockerfile
  example/cmd/publisher/Dockerfile
Labels: size/XS

#150 Fix new pb
  pagebuilder/editor.go
Labels: size/XS

#38 show crop error
  .github/workflows/go.yml
  example/admin/config.go
  media/integration/integration_test.go
  media/upload.go
  media/views/cropper.go
  media/views/filechooser.go
  media/views/media_box.go
  pagebuilder/example/config.go
Labels: size/M

#147 New pb
  example/admin/config.go
  go.mod
  go.sum
  l10n/interface.go
  note/actions.go
  note/config.go
  note/helper.go
  pagebuilder/builder.go
  pagebuilder/content.go
  pagebuilder/editor.go
  pagebuilder/example/config.go
  pagebuilder/example/containers/brand_grid.go
  pagebuilder/example/containers/common.go
  pagebuilder/example/containers/contact_form.go
  pagebuilder/example/containers/footer.go
  pagebuilder/example/containers/header.go
  pagebuilder/example/containers/heading.go
  pagebuilder/example/containers/image.go
  pagebuilder/example/containers/in_numbers.go
  pagebuilder/example/containers/list_content.go
  pagebuilder/example/containers/list_content_lite.go
  pagebuilder/example/containers/list_content_with_image.go
  pagebuilder/example/containers/page_title.go
  pagebuilder/example/containers/video_banner.go
  pagebuilder/example/examplemain/main.go
  pagebuilder/example/integration_test.go
  pagebuilder/messages.go
  pagebuilder/models.go
  pagebuilder/settings.go
  presets/detailing.go
  presets/editing.go
  presets/listing.go
  presets/presets.go
  publish/views/config.go
  publish/views/events.go
  publish/views/schedule.go
  publish/views/status.go
  publish/views/versions.go
  seo/admin.go
  seo/admin_test.go
  seo/collection.go
  seo/model.go
Labels: size/XXL

#153 Fix pb template preview
  pagebuilder/builder.go
Labels: size/M

#152 Fix typo and sort imports and rename stuff
  pagebuilder/builder.go
  pagebuilder/content.go
  pagebuilder/editor.go
  pagebuilder/models.go
  pagebuilder/settings.go
  pagebuilder/update_shadow.sh
Labels: size/L

#154 Show online url on pb page state card
  pagebuilder/publish.go
  pagebuilder/settings.go
Labels: size/S

#156 listeditor: support custom event
  presets/field.go
  presets/listeditor.go
Labels: size/M

#157 richeditor: raw config
  go.mod
  go.sum
  richeditor/richeditor.go
Labels: size/S

#158 media_oss acl S3CannedAccessControlListBucketOwnerFullControl
  example/admin/config.go
Labels: size/XS

#159 Fix PB
  pagebuilder/builder.go
Labels: size/M

#160 seo: add AfterSave hook
  seo/admin.go
  seo/collection.go
Labels: size/S

#161 new mux to avoid default net/http/pprof impact
  example/main.go
Labels: size/S

#162 PB template optional
  pagebuilder/builder.go
Labels: size/L
