Repository qor5/admin, pull requests merged in 2023-09, with the labels that each got.

#163 Fix pb path regex to support `-`
  pagebuilder/helper.go
Labels: size/XS

#164 fix preview page html layout
  go.mod
  go.sum
  pagebuilder/builder.go
  pagebuilder/content.go
  pagebuilder/editor.go
  pagebuilder/example/layouts/page_layout.go
Labels: size/M

#165 Fix pb invalid slug panic
  pagebuilder/builder.go
  presets/api.go
Labels: size/S

#168 presets: append fields to layout
  presets/field.go
Labels: size/M

#169 media: fix crop with hash MediaLibraryURL
  media/views/cropper.go
Labels: size/XS

#170 media vips: fix default size key
  media/vips/vips.go
Labels: size/XS

#171 remove EditPageContent button
  pagebuilder/builder.go
  pagebuilder/messages.go
Labels: size/M

#172 use Drawer for container form
  pagebuilder/builder.go
  pagebuilder/editor.go
Labels: size/S

#173 Fix uppercase letters on pb slug
  pagebuilder/helper.go
  pagebuilder/helper_test.go
Labels: size/M

#174 upgrade qor5/ui
  go.mod
  go.sum
Labels: size/XS

#167 modify l10n Configure
  example/admin/config.go
  l10n/l10n.go
  l10n/views/config.go
  l10n/views/events.go
Labels: size/M

#176 modify localizeContainersToAnotherPage
  pagebuilder/editor.go
Labels: size/M

#178 Modify pb
  example/admin/data_init.go
  pagebuilder/editor.go
  pagebuilder/models.go
  publish/views/versions.go
Labels: size/M

#177 Fix missing URL for uploading non image files
  media/upload.go
Labels: size/XS

#179 upgrade go to 1.21.1
  example/Dockerfile
  example/cmd/data-resetor/Dockerfile
  example/cmd/publisher/Dockerfile
Labels: size/XS

#175 open graph title,description,meta data
  seo/admin.go
  seo/collection.go
  seo/messages.go
  seo/model.go
  seo/model_test.go
Labels: size/L

#180 Worker add shutdown
  worker/action_job.go
  worker/builder.go
  worker/cron.go
  worker/goque.go
  worker/integration_test/test_que.go
  worker/mock/queue.go
  worker/queue.go
Labels: size/L

#181 Fix example init sql
  example/admin/data_init.go
Labels: size/XS

#182 add shared containers mgmt page rename
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/messages.go
Labels: size/M

#183 upgrade web
  go.mod
  go.sum
Labels: size/XS

#166 Fix security issues
  example/admin/auth.go
  example/admin/middlewares.go
  example/admin/router.go
  go.mod
  go.sum
Labels: size/M

#185 Only display counter on seo textfield instead of limit
  seo/admin.go
Labels: size/XS

#184 fix StatusBar in edit form
  example/admin/category_config.go
  example/admin/config.go
  example/admin/product_config.go
  pagebuilder/builder.go
  presets/field.go
  publish/views/config.go
  publish/views/status.go
Labels: size/M

#187 Fix auto fill seo when useing custom seo with blank settings
  seo/admin.go
Labels: size/XS
