Repository qor5/admin, pull requests merged in 2023-11, with the labels that each got.

#212 fix slug auto sync don't work properly
  slug/field.go
Labels: size/XS

#213 fix editing form for seo
  pagebuilder/builder.go
  seo/admin.go
Labels: size/S

#215 Fix example oauth login
  example/admin/auth.go
  example/models/user.go
Labels: size/S

#216 Erase all the public users data on interval db reset
  example/admin/data_init.go
  example/cmd/data-resetor/main.go
Labels: size/M

#217 add registration date for user
  example/admin/auth.go
Labels: size/XS

#218 remove oauth complete info page
  example/admin/auth.go
  example/admin/login_views.go
  example/admin/middlewares.go
  example/admin/router.go
  example/models/user.go
Labels: size/L

#220 upgrade ui
  go.mod
  go.sum
Labels: size/XS

#222 fix some mistakes in comment and a little bug
  seo/collection.go
  seo/model.go
Labels: size/M

#224 fixed the issue where empty datas were returned after executing filter
  go.mod
  go.sum
  presets/listing.go
Labels: size/XS

#228 presets: fix Except()
  presets/detailing.go
  presets/editing.go
  presets/field.go
  presets/listing.go
Labels: size/S

#229 fix pb seo Title Variable
  pagebuilder/builder.go
Labels: size/XS
