Repository qor5/admin, pull requests merged in 2024-09, with the labels that each got.

#541 activity: view all
  activity/admin.go
  activity/builder.go
  activity/builder_test.go
  activity/messages.go
  activity/model_builder.go
  activity/timeline.go
  docs/docsrc/examples/examples_admin/activity.go
  docs/docsrc/examples/examples_admin/activity_test.go
Labels: size/L

#542 publish: LiveCol min-width && next schedule tooltip && ShowSnackbarScript at ThenScript
  activity/admin.go
  activity/timeline.go
  docs/docsrc/examples/examples_admin/publish_test.go
  docs/docsrc/examples/examples_admin/publish_test/flow_publish_test.go
  publish/builder.go
  publish/messages.go
  publish/publish_event.go
  publish/status_compo.go
Labels: size/L

#540 Feat UI reborn
  docs/docsrc/examples/examples_presets/listing.go
  docs/docsrc/examples/examples_presets/listing_test.go
  docs/docsrc/examples/examples_presets/mux.go
  go.mod
  go.sum
  presets/messages.go
  presets/row_menu.go
Labels: size/M

#544 publish: add DisableDataChangeTracking for pagebuilder editor
  activity/builder.go
  docs/docsrc/examples/examples_admin/activity_test.go
  pagebuilder/editor.go
  publish/version_compo.go
Labels: size/M

#543 listing: add WrapTable && presets: cfTime Disabled
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  go.sum
  presets/field_defaults.go
  presets/listing_builder.go
  presets/listing_compo.go
Labels: size/M

#545 add public template
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  pagebuilder/builder.go
  pagebuilder/messages.go
  pagebuilder/model.go
  pagebuilder/page.go
  pagebuilder/template.go
Labels: size/L

#546 activity: fix view all redirect
  activity/timeline.go
  presets/presets.go
Labels: size/S

#547 activity: fix delete note
  activity/timeline.go
Labels: size/XS

#548 fix messages
  pagebuilder/messages.go
  pagebuilder/template.go
Labels: size/M

#553 presets: add LazyWrapComponentFunc and LazyWrapSetterFunc
  docs/docsrc/examples/examples_presets/editing.go
  docs/docsrc/examples/examples_presets/editing_test.go
  pagebuilder/template.go
  presets/field.go
  presets/listing_builder.go
  presets/presets_test.go
  presets/section.go
Labels: size/L

#555 deepsource: fix some simple
  autocomplete/model.go
  media/base/base.go
  media/filechooser.go
  media/media_library/media_library.go
  presets/integration/example_test.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
  utils/testflow/gentool/main.go
  utils/testflow/gentool/step.go
Labels: size/M

#556 slug: fix auto sync from
  docs/docsrc/examples/examples_admin/mux.go
  docs/docsrc/examples/examples_admin/slug.go
  docs/docsrc/examples/examples_admin/slug_test.go
  example/admin/config.go
  go.mod
  go.sum
  presets/editing.go
  presets/field_defaults.go
  slug/field.go
  slug/messages.go
Labels: size/L

#557 add linkage_select_filter;autocomplate support object
  autocomplete/builder.go
  autocomplete/integration/autocomplete_test.go
  autocomplete/model.go
  docs/docsrc/examples/examples_admin/autocomplete.go
  docs/docsrc/examples/examples_admin/autocomplete_test.go
  docs/docsrc/examples/examples_admin/linkage_select_filter_item_remote.go
  docs/docsrc/examples/examples_admin/linkage_select_filter_item_remote_server.go
  docs/docsrc/examples/examples_admin/linkage_select_filter_item_remote_server_test.go
  docs/docsrc/examples/examples_admin/linkage_select_filter_item_remote_test.go
  docs/docsrc/examples/examples_admin/mux.go
  docs/docsrc/examples/examples_admin/server/main.go
  docs/docsrc/examples/utils.go
  go.mod
  go.sum
Labels: size/XL

#559 fix selected empty
  docs/docsrc/examples/examples_admin/linkage_select_filter_item_remote.go
  docs/docsrc/examples/examples_admin/linkage_select_filter_item_remote_test.go
  go.mod
  go.sum
Labels: size/S

#558 Feat tabs field
  activity/admin.go
  activity/model_builder.go
  activity/util.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/publish.go
  docs/docsrc/examples/examples_presets/detailing.go
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/mux.go
  example/admin/user_config.go
  example/models/category.go
  example/models/l10n_model_with_version.go
  example/models/list_model.go
  example/models/post.go
  example/models/product.go
  login/example/main.go
  microsite/microsite.go
  presets/field.go
  presets/listing_compo.go
  presets/section.go
  presets/tabsFieldBuilder.go
  publish/builder.go
  publish/interfaces.go
  publish/publish_event.go
  publish/publish_test.go
  publish/schedule_publish_builder.go
Labels: size/XL

#562 upgrade x
  go.mod
  go.sum
Labels: size/XS

#563 fix template editing no translate
  pagebuilder/template.go
Labels: size/XS

#561 Support after title comp without drawer
  docs/docsrc/examples/examples_presets/detailing.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/mux.go
  presets/menu_group.go
  presets/menu_order.go
  presets/presets.go
  presets/presets_test.go
Labels: size/XL

#565 filter dateoptions
  docs/docsrc/examples/examples_admin/media_allow_types.go
  docs/docsrc/examples/examples_admin/media_allow_types_test.go
  docs/docsrc/examples/examples_presets/listing.go
  docs/docsrc/examples/examples_presets/listing_test.go
  go.mod
  go.sum
  media/builder.go
  media/filechooser.go
Labels: size/M

#566 fix page creating
  example/integration/pagebuilder_template_test.go
  example/integration/pagebuilder_test.go
  pagebuilder/model_events.go
  pagebuilder/page.go
Labels: size/M

#564 slug => autosync
  .deepsource.toml
  autosync/autosync.go
  docs/docsrc/examples/examples_admin/activity_test.go
  docs/docsrc/examples/examples_admin/autosync.go
  docs/docsrc/examples/examples_admin/autosync_test.go
  docs/docsrc/examples/examples_admin/mux.go
  docs/docsrc/examples/examples_admin/slug.go
  docs/docsrc/examples/examples_admin/slug_test.go
  example/admin/config.go
  example/models/post.go
  go.mod
  go.sum
  slug/README.md
  slug/field.go
  slug/messages.go
  slug/slug_test.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/XL

#568 listing: filter datepicker i18n
  go.mod
  go.sum
  presets/listing_compo.go
  presets/messages.go
Labels: size/S

#569 fix: kak filter comp style problem
  presets/listing_compo.go
Labels: size/XS

#570 fix container creating
  example/integration/pagebuilder_test.go
  pagebuilder/example/containers/brand_grid.go
  pagebuilder/model.go
Labels: size/M

#571 fix split param error
  example/integration/media_test.go
  media/builder.go
  media/filechooser.go
Labels: size/M

#572 pagebuilder: keep scrollTop after add/delete row
  go.sum
  pagebuilder/builder.go
  pagebuilder/editor.go
Labels: size/M

#573 fix demo container list active
  example/integration/pagebuilder_share_test.go
  example/integration/pagebuilder_test.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/publish_test.go
  pagebuilder/settings.go
Labels: size/L

#575 Feat tabs section order
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/mux.go
  presets/field.go
  presets/tabsFieldBuilder.go
Labels: size/L

#574 richeditor/media_box: add ErrorMessages and Disabled
  docs/docsrc/examples/examples_presets/editing.go
  docs/docsrc/examples/examples_presets/editing_test.go
  media/media_box.go
  richeditor/redactor/redactor.custom.css
  richeditor/richeditor.go
Labels: size/L

#576 upgrade x
  go.mod
  go.sum
Labels: size/XS

#577 upgrade x
  go.mod
  go.sum
Labels: size/XS

#578 Refactor section save func
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  presets/detailing.go
  presets/section.go
Labels: size/L

#580 Refactor create menu
  presets/menu_order.go
Labels: size/L

#579 chore: update the version of x
  go.mod
  go.sum
Labels: size/XS

#581 filter add validate
  docs/docsrc/examples/examples_presets/listing.go
  docs/docsrc/examples/examples_presets/listing_test.go
  docs/docsrc/examples/examples_vuetifyx/filter-demo.go
  go.mod
  go.sum
  pagebuilder/messages.go
  presets/listing_compo.go
Labels: size/M

#582 Fix menu group item permission
  docs/docsrc/examples/examples_presets/menu.go
  docs/docsrc/examples/examples_presets/menu_test.go
  docs/docsrc/examples/examples_presets/mux.go
  presets/menu_order.go
Labels: size/M

#583 tiptap editor
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/editing.go
  docs/docsrc/examples/examples_presets/editing_test.go
  docs/docsrc/examples/examples_presets/mux.go
  go.mod
  go.sum
  media/media_box.go
  tiptap/embed.go
  tiptap/embed/github.css
  tiptap/embed/github.css.map
  tiptap/embed/github.scss
  tiptap/tiptap.go
Labels: size/XXL

#584 pagebuilder add PreviewOpenNewTab
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  example/integration/pagebuilder_test.go
  pagebuilder/builder.go
  pagebuilder/settings.go
Labels: size/S

#585 web/v3 v3.0.8 && x/v3 v3.0.9
  go.mod
  go.sum
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/S

#587 after addrow scroll to add row btn
  pagebuilder/builder.go
  presets/listeditor.go
Labels: size/S

#586 Feat UI reborn
  activity/timeline.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  go.mod
  go.sum
  media/media_box.go
  pagebuilder/editor.go
  pagebuilder/page.go
  pagebuilder/settings.go
  presets/common_page.go
  presets/section.go
  publish/status_compo.go
  publish/version_compo.go
Labels: size/L

#589 Section supports simultaneous display field error with globe err
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  go.mod
  go.sum
  presets/detailing.go
Labels: size/M

#590 Fix the Page Builder versions count
  pagebuilder/page.go
Labels: size/XS

#591 pagebuilder: fix detail page title
  pagebuilder/builder.go
Labels: size/XS

#592 page only fields
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  example/integration/pagebuilder_test.go
  go.mod
  go.sum
  pagebuilder/builder.go
  pagebuilder/page.go
  pagebuilder/settings.go
  utils/slice.go
Labels: size/L

#593 upgrade x
  go.mod
  go.sum
Labels: size/XS

#588 style: style adjusting
  docs/docsrc/examples/examples_presets/detailing.go
  docs/docsrc/examples/examples_presets/dialog_test.go
  docs/docsrc/examples/examples_presets/mux.go
  go.mod
  go.sum
  presets/detailing.go
  presets/field.go
  presets/presets.go
  publish/version_compo.go
  utils/confirm_dialog.go
  utils/messages.go
Labels: size/L

#594 Fix seo
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  docs/docsrc/examples/examples_admin/seo.go
  docs/docsrc/examples/examples_admin/seo_test.go
  docs/docsrc/examples/examples_presets/listing.go
  docs/docsrc/examples/examples_presets/listing_test.go
  docs/docsrc/examples/examples_presets/perm_role_test.go
  example/integration/pagebuilder_test.go
  go.mod
  go.sum
  pagebuilder/builder.go
  pagebuilder/example/containers/heading.go
  pagebuilder/helper.go
  pagebuilder/page.go
  pagebuilder/settings.go
  pagebuilder/template_events.go
  presets/field.go
  presets/field_defaults.go
  presets/integration/fields_test.go
  presets/section.go
  seo/admin.go
  seo/messages.go
Labels: size/XL

#595 chore: update the version of x
  go.mod
  go.sum
Labels: size/XS

#596 fix VXLinkageSelectRemote modelvalue
  docs/docsrc/examples/examples_admin/linkage_select_filter_item_remote.go
  go.mod
  go.sum
Labels: size/S

#598 support editing setter return global error
  docs/docsrc/examples/examples_presets/editing.go
  docs/docsrc/examples/examples_presets/editing_test.go
  go.mod
  go.sum
  presets/field.go
Labels: size/M

#599 chore: update x and add width api to common dialog
  go.mod
  go.sum
  utils/confirm_dialog.go
Labels: size/XS

#600 relay pagination
  activity/admin.go
  activity/builder.go
  activity/model_builder.go
  docs/docsrc/examples/examples_admin/listing.go
  docs/docsrc/examples/examples_admin/listing_test.go
  docs/docsrc/examples/examples_presets/listing.go
  example/admin/config.go
  example/admin/user_config.go
  go.mod
  go.sum
  l10n/builder.go
  pagebuilder/builder.go
  pagebuilder/template.go
  presets/api.go
  presets/gorm2op/operator.go
  presets/gorm2op/relay.go
  presets/gormop/operator.go
  presets/listing_builder.go
  presets/listing_compo.go
  presets/nested_many.go
  publish/builder.go
  publish/version_compo.go
  seo/admin.go
Labels: size/XXL

#601 fix page detail name to formkey
  example/integration/pagebuilder_test.go
  pagebuilder/page.go
  pagebuilder/settings.go
Labels: size/S

#602 upgrade relay version
  docs/docsrc/examples/examples_presets/listing.go
  go.mod
  go.sum
Labels: size/S

#603 fix Pagebuilder context key to empty struct
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  pagebuilder/editor.go
  pagebuilder/model.go
Labels: size/M

#605 publish: Add ContextWithAppendDeferFunc
  docs/docsrc/examples/examples_admin/publish.go
  example/cmd/publisher/main.go
  publish/builder.go
  publish/list_publish_builder.go
  publish/publish_test.go
  publish/schedule_publish_builder.go
  publish/utils.go
Labels: size/L

#607 fix: https://theplanttokyo.atlassian.net/browse/KAK-6057
  go.mod
  go.sum
Labels: size/XS

#610 Fix section edit button unclickable
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/mux.go
  presets/section.go
Labels: size/M

#612 chore: replace v-dialog with vx-dialog and fix bugs
  go.mod
  go.sum
  login/view_common.go
  login/views.go
  presets/integration/example_test.go
  presets/messages.go
  presets/presets.go
Labels: size/L

#614 field_defaults: use vxcheckbox
  docs/docsrc/examples/examples_admin/activity.go
  go.mod
  go.sum
  presets/field_defaults.go
  presets/integration/fields_test.go
  presets/messages.go
Labels: size/M

#613 add ConfirmDialogTitleText
  docs/docsrc/examples/examples_presets/confirm-dialog.go
  docs/docsrc/examples/examples_presets/confirm-dialog_test.go
  media/media_box.go
  media/messages.go
  presets/messages.go
  presets/presets.go
  publish/messages.go
Labels: size/L

#616 upgrade x to v3.0.10
  go.mod
  go.sum
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/S

#617 Feat UI reborn3
  go.mod
  go.sum
  pagebuilder/editor.go
Labels: size/M

#618 feat: optimize the look of folded status
  pagebuilder/editor.go
Labels: size/XS

#619 fix seo i18n messages
  seo/admin.go
  seo/messages.go
Labels: size/XS
