Repository qor5/admin, pull requests merged in 2024-10, with the labels that each got.

#621 Feat UI reborn3
  docs/docsrc/examples/examples_admin/media_test.go
  docs/docsrc/examples/examples_admin/publish_test.go
  docs/docsrc/examples/examples_admin/publish_test/flow_schedule_test.go
  example/integration/media_test.go
  go.mod
  go.sum
  media/filechooser.go
  media/media_box.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/messages.go
  pagebuilder/model_events.go
  pagebuilder/template.go
  presets/field_defaults.go
  presets/integration/fields_test.go
  presets/listing_builder.go
  presets/listing_compo.go
  publish/schedule_event.go
  publish/version_event.go
Labels: size/L

#623 Feat UI reborn2
  go.mod
  go.sum
  presets/field_defaults.go
Labels: size/S

#625 fix auto save edit reload from sever; fix pagebuilder ,template permi…
  cmd/qor5/website-template/admin/config.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  example/admin/config.go
  example/integration/pagebuilder_test.go
  go.mod
  go.sum
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/example/config.go
  pagebuilder/example/containers/heading.go
  pagebuilder/example/examplemain/main.go
  pagebuilder/publish_test.go
  pagebuilder/template.go
  presets/field.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/L

#626 Editing add field section class wrap
  docs/docsrc/examples/examples_presets/editing.go
  docs/docsrc/examples/examples_presets/editing_test.go
  presets/editing.go
Labels: size/M

#628 Fix preview
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  example/integration/pagebuilder_test.go
  pagebuilder/builder.go
  pagebuilder/model.go
  pagebuilder/page_layout.go
  pagebuilder/template.go
Labels: size/M

#622 upgrade relay to v0.2.1
  go.mod
  go.sum
  pagebuilder/builder.go
  pagebuilder/template.go
  presets/api.go
  presets/gorm2op/operator.go
  presets/gorm2op/relay.go
  presets/listing_compo.go
Labels: size/L

#629 perm: resource parts tidy && customizable verifier for model builder
  cmd/qor5/website-template/admin/integration_test.go
  docs/docsrc/examples/examples_admin/media_allow_types_test.go
  docs/docsrc/examples/examples_admin/media_test.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  docs/docsrc/examples/examples_admin/publish.go
  docs/docsrc/examples/examples_admin/singleton_test.go
  docs/docsrc/examples/examples_presets/menu.go
  example/integration/media_test.go
  example/integration/pagebuilder_template_test.go
  example/integration/pagebuilder_test.go
  go.mod
  go.sum
  media/builder.go
  media/list.go
  media/media_box.go
  media/perm.go
  pagebuilder/builder.go
  presets/editing.go
  presets/menu_order.go
  presets/model.go
  presets/presets.go
  publish/version_compo.go
  utils/testflow/gentool/go.sum
Labels: size/XL

#631 demo case for vx library
  example/admin/config.go
  example/admin/demo_case.go
  example/integration/demo_case_test.go
Labels: size/L

#632 fix media uriname;fix demo case view field
  example/admin/demo_case.go
  media/filechooser.go
  media/list.go
Labels: size/XS

#633 upgrade x to v3.0.11
  go.mod
  go.sum
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/S

#634 fix container category viewer disabled;
  example/integration/demo_containers_test.go
  example/integration/pagebuilder_test.go
  pagebuilder/builder.go
  pagebuilder/example/containers/common.go
  pagebuilder/example/containers/header.go
  pagebuilder/example/containers/heading.go
  pagebuilder/example/containers/image.go
  pagebuilder/example/containers/list_content.go
  pagebuilder/example/containers/list_content_lite.go
  pagebuilder/example/containers/video_banner.go
  pagebuilder/helper.go
  presets/field_defaults.go
Labels: size/L

#635 activity: add perm actions
  activity/perm.go
  activity/timeline.go
  docs/docsrc/examples/examples_admin/activity_test.go
Labels: size/L

#640 fix pageBuilder presets listing view redirect
  example/integration/pagebuilder_test.go
  pagebuilder/builder.go
Labels: size/M

#639 activity: add PermListNotes to the activity
  activity/model_builder.go
  activity/perm.go
  docs/docsrc/examples/examples_admin/activity_test.go
Labels: size/S

#638 form: fix the display error when `HasPermCreate&&NoPermUpdate` && hide button if no permission
  presets/editing.go
  presets/field.go
Labels: size/M

#641 activity_logs: user cursor based pagination
  activity/admin.go
  docs/docsrc/examples/examples_admin/activity_test.go
Labels: size/M

#636 restore qor5 example
  hack/build-deploy-app.sh
  plantbuild/build.jsonnet
  plantbuild/images.jsonnet
Labels: size/XS

#642 presets: snackbar for presetsMessage support multiline text
  presets/presets.go
Labels: size/XS

#643 other snackbars support multiline text display
  pagebuilder/editor.go
  presets/detailing.go
  presets/editing.go
  presets/presets.go
Labels: size/S

#644 change richeditor to tiptap
  docs/docsrc/content/basics/editing-customizations.go
  docs/docsrc/examples/examples_admin/layout.go
  docs/docsrc/examples/examples_presets/editing.go
  docs/docsrc/examples/examples_presets/editing_test.go
  example/admin/config.go
  example/integration/demo_containers_test.go
  example/integration/post_test.go
  example/pages/settings.go
  pagebuilder/builder.go
  pagebuilder/example/config.go
  pagebuilder/example/containers/heading.go
  pagebuilder/example/containers/list_content_lite.go
Labels: size/L

#645 fix snackbar multiline display for static text
  activity/admin.go
  activity/timeline.go
  presets/detailing.go
  presets/editing.go
  publish/status_compo.go
Labels: size/S

#646 pagebuilder readd richeditor
  pagebuilder/builder.go
Labels: size/XS

#647 feat: use new password comp + add demo case
  docs/docsrc/examples/examples_admin/login_test.go
  example/admin/demo_case.go
  go.mod
  go.sum
  login/view_common.go
Labels: size/M

#649 fix demo case view Marshal;fix reload focus ;add ReplicateContainerE…
  example/admin/demo_case.go
  example/integration/demo_case_test.go
  example/integration/pagebuilder_share_test.go
  example/integration/pagebuilder_test.go
  go.mod
  go.sum
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/model_events.go
  presets/gorm2op/operator.go
  presets/gorm2op/relay.go
  tiptap/tiptap.go
Labels: size/L

#651 democase remove autofocus
  example/admin/demo_case.go
Labels: size/XS

#652 release test
  example/admin/demo_case.go
  example/integration/demo_case_test.go
  example/integration/pagebuilder_share_test.go
  example/integration/pagebuilder_test.go
  go.mod
  go.sum
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/model_events.go
  presets/gorm2op/operator.go
  presets/gorm2op/relay.go
  tiptap/tiptap.go
Labels: size/L

#654 publish: SchedulePublisherDBScope => SchedulePublishDBScope/ScheduleUnPublishDBScope
  publish/publish_test.go
  publish/schedule_publish_builder.go
Labels: size/L

#656 Page add PagePermissionRN
  pagebuilder/models.go
Labels: size/XS

#655 fielddefaults: empty time displays empty && default readonlytext for DETAIL && treated like scalar if not specified
  docs/docsrc/examples/examples_admin/activity.go
  presets/field.go
  presets/field_defaults.go
  presets/integration/fields_test.go
Labels: size/L

#659 add replicate container
  example/integration/pagebuilder_share_test.go
  example/integration/pagebuilder_test.go
  pagebuilder/messages.go
  pagebuilder/model.go
  pagebuilder/model_events.go
Labels: size/L

#660 test
  docs/docsrc/examples/examples_admin/activity.go
  example/integration/pagebuilder_share_test.go
  example/integration/pagebuilder_test.go
  pagebuilder/messages.go
  pagebuilder/model.go
  pagebuilder/model_events.go
  pagebuilder/models.go
  presets/field.go
  presets/field_defaults.go
  presets/integration/fields_test.go
  publish/publish_test.go
  publish/schedule_publish_builder.go
Labels: size/XL

#658 activity: public WrapperSaveFunc
  activity/model_builder.go
Labels: size/L

#661 fix pagebuilder PrimarySlugInterface
  pagebuilder/builder.go
  pagebuilder/model.go
  pagebuilder/model_events.go
  pagebuilder/models.go
  pagebuilder/page.go
  pagebuilder/settings.go
  pagebuilder/template.go
Labels: size/M

#663 AWS_REGION change to DB_RESET for show count down
  example/admin/config.go
  example/integration/activity_logs_test.go
  example/integration/list_model_test.go
  example/integration/post_test.go
  example/integration/profile_test.go
Labels: size/L

#664 remove countdown
  activity/model_builder.go
  example/admin/config.go
  example/integration/activity_logs_test.go
  example/integration/list_model_test.go
  example/integration/post_test.go
  example/integration/profile_test.go
  pagebuilder/builder.go
  pagebuilder/model.go
  pagebuilder/model_events.go
  pagebuilder/models.go
  pagebuilder/page.go
  pagebuilder/settings.go
  pagebuilder/template.go
Labels: size/XL

#648 Refactor section: support reuse section in editing
  docs/docsrc/examples/examples_admin/activity.go
  docs/docsrc/examples/examples_admin/autosync.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  docs/docsrc/examples/examples_admin/publish.go
  docs/docsrc/examples/examples_admin/seo_test.go
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/editing.go
  docs/docsrc/examples/examples_presets/editing_test.go
  docs/docsrc/examples/examples_presets/mux.go
  docs/docsrc/examples/examples_presets/perm_role_test.go
  example/admin/config.go
  example/admin/demo_case.go
  example/integration/demo_case_test.go
  example/integration/pagebuilder_test.go
  example/integration/post_test.go
  pagebuilder/page.go
  pagebuilder/settings.go
  presets/actions/const.go
  presets/detailing.go
  presets/editing.go
  presets/field.go
  presets/field_tabs.go
  presets/integration/section_test.go
  presets/listing_builder.go
  presets/model.go
  presets/section.go
  publish/builder.go
  seo/admin.go
Labels: size/XXL

#662 publish: fix transaction issues for Publish/Unpublish
  publish/builder.go
  publish/publish_test.go
Labels: size/L

#665 worker add config to use
  example/admin/config.go
  example/admin/router.go
  example/cmd/publisher/main.go
  example/integration/pagebuilder_test.go
  example/integration/post_test.go
  media/media_box.go
  worker/builder.go
Labels: size/M

#666 fix democase VXField No Disabled and Clearable;AutoComplate add Closa…
  example/admin/demo_case.go
  go.mod
  go.sum
Labels: size/S

#667 test
  docs/docsrc/examples/examples_admin/activity.go
  docs/docsrc/examples/examples_admin/autosync.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  docs/docsrc/examples/examples_admin/publish.go
  docs/docsrc/examples/examples_admin/seo_test.go
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/editing.go
  docs/docsrc/examples/examples_presets/editing_test.go
  docs/docsrc/examples/examples_presets/mux.go
  docs/docsrc/examples/examples_presets/perm_role_test.go
  example/admin/config.go
  example/admin/demo_case.go
  example/admin/router.go
  example/cmd/publisher/main.go
  example/integration/demo_case_test.go
  example/integration/pagebuilder_test.go
  example/integration/post_test.go
  go.mod
  go.sum
  media/media_box.go
  pagebuilder/page.go
  pagebuilder/settings.go
  presets/actions/const.go
  presets/detailing.go
  presets/editing.go
  presets/field.go
  presets/field_tabs.go
  presets/integration/section_test.go
  presets/listing_builder.go
  presets/model.go
  presets/section.go
  publish/builder.go
  publish/publish_test.go
  seo/admin.go
  worker/builder.go
Labels: size/XXL

#669 Feat UI reborn3
  example/admin/demo_case.go
  go.mod
  go.sum
Labels: size/XS

#671 Feat UI reborn2
  example/admin/demo_case.go
Labels: size/XS

#676 Feat date picker
  example/admin/demo_case.go
  example/integration/demo_case_test.go
  go.mod
  go.sum
  presets/listeditor.go
Labels: size/L

#674 activity: add BeforeCreate for it's model builder
  activity/model_builder.go
  docs/docsrc/examples/examples_admin/activity.go
  docs/docsrc/examples/examples_admin/activity_test.go
Labels: size/L

#678 demo case add avatar,dialog password number;
  example/admin/demo_case.go
  example/integration/demo_case_test.go
Labels: size/L

#677 feat: support https://theplanttokyo.atlassian.net/browse/QOR5-412
  pagebuilder/editor.go
Labels: size/M

#680 fix demo case dialog show
  example/admin/demo_case.go
  go.mod
  go.sum
Labels: size/M

#681 democase dialog
  example/admin/demo_case.go
  go.mod
  go.sum
  pagebuilder/editor.go
Labels: size/M

#682 feat: support prepend slot + style of vx-label
  go.mod
  go.sum
Labels: size/XS

#683 ugrade x to v3.0.12
  go.mod
  go.sum
Labels: size/S

#687 Fix daterange
  example/admin/demo_case.go
  go.mod
  go.sum
Labels: size/S

#688 fix democase date range validate condition
  example/admin/demo_case.go
Labels: size/XS

#684 Feat section remove prefix, and refactor
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/editing_test.go
  docs/docsrc/examples/examples_presets/perm_role_test.go
  example/admin/demo_case.go
  example/integration/demo_case_test.go
  example/integration/pagebuilder_test.go
  example/integration/post_test.go
  presets/editing.go
  presets/section.go
  seo/admin.go
Labels: size/XL

#689 Add section validate only used in detailing
  example/admin/demo_case.go
  presets/section.go
Labels: size/M

#690 chore: update x
  go.mod
  go.sum
Labels: size/XS

#693 Fix pageBuilder validator wrong when save section
  pagebuilder/page.go
Labels: size/S

#692 feat validate;restore delete row icon position
  docs/docsrc/examples/examples_presets/perm_role_test.go
  example/admin/demo_case.go
  example/integration/demo_case_test.go
  example/integration/pagebuilder_test.go
  go.mod
  go.sum
  pagebuilder/builder.go
  pagebuilder/example/containers/in_numbers.go
  pagebuilder/helper.go
  pagebuilder/page.go
  pagebuilder/settings.go
  presets/actions/const.go
  presets/api.go
  presets/const.go
  presets/detailing.go
  presets/editing.go
  presets/field.go
  presets/field_defaults.go
  presets/integration/example_test.go
  presets/integration/fields_test.go
  presets/listeditor.go
  presets/listener.go
  presets/model.go
  presets/section.go
  presets/utils.go
Labels: size/XXL
