Repository qor5/admin, pull requests merged in 2024-07, with the labels that each got.

#292 fix: `Code is required` is displayed in the wrong field
  example/admin/product_config.go
Labels: size/XS

#293 Feat support section validator
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  presets/integration/section_test.go
  presets/section.go
Labels: size/M

#294 Feat Media use AutoMigrate() instead of disAutoMigrate
  example/admin/config.go
  media/builder.go
  media/media_box.go
Labels: size/S

#295 fix seo activity migrate
  activity/activity.go
  activity/activity_test.go
  cmd/qor5/website-template/admin/config.go
  docs/docsrc/examples/examples_admin/activity.go
  docs/docsrc/examples/examples_admin/seo.go
  example/admin/config.go
  example/admin/seo.go
  pagebuilder/example/integration_test.go
  seo/admin_test.go
  seo/builder.go
  seo/builder_test.go
  seo/render_test.go
Labels: size/L

#296 remove AutoMigrate
  seo/builder.go
Labels: size/XS

#297 fix Multiple-Column Indexes has zero value will inert; seo add AutoMi…
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  example/integration/pagebuilder_test.go
  presets/gorm2op/operator.go
  seo/builder.go
Labels: size/L

#298 fix bug that can not publish
  publish/builder.go
  publish/schedule_event.go
  publish/schedule_publish_builder.go
  publish/version.go
Labels: size/M

#299 use seoBuilder add seo detail
  pagebuilder/builder.go
Labels: size/XS

#300 fix update zero value
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  presets/gorm2op/operator.go
Labels: size/M

#301 Feat pagebuilder
  cmd/qor5/website-template/admin/integration_test.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  example/integration/pagebuilder_test.go
  pagebuilder/builder.go
  pagebuilder/content.go
  pagebuilder/editor.go
  pagebuilder/example/integration_test.go
  pagebuilder/model.go
  publish/builder.go
Labels: size/XXL

#282 activity
  .github/codecov.yml
  .gitignore
  README.md
  activity/README.md
  activity/activity.go
  activity/activity_log.go
  activity/activity_model.go
  activity/admin.go
  activity/builder.go
  activity/builder_test.go
  activity/log_diff.go
  activity/log_diff_test.go
  activity/log_helpers.go
  activity/messages.go
  activity/model_builder.go
  activity/note.go
  activity/note_actions.go
  cmd/qor5/website-template/admin/config.go
  docs/docs/basics/login.html
  docs/docsrc/content/advanced-functions/detail-page-for-complex-object.go
  docs/docsrc/content/basics/login.go
  docs/docsrc/examples/examples_admin/activity.go
  docs/docsrc/examples/examples_admin/activity_test.go
  docs/docsrc/examples/examples_admin/publish.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/listing.go
  example/admin/config.go
  example/admin/middlewares.go
  example/admin/note.go
  example/admin/perm.go
  example/admin/router.go
  example/admin/user_config.go
  go.mod
  l10n/events.go
  note/actions.go
  note/builder.go
  note/config.go
  note/helper.go
  note/messages.go
  note/note.go
  pagebuilder/builder.go
  presets/examples/setup.go
  presets/model.go
  presets/presets.go
  publish/builder.go
  publish/version_compo.go
  worker/action_job.go
  worker/builder.go
Labels: size/XXL

#302 FieldInstall / InlineListing => NestedMany
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/mux.go
  go.mod
  go.sum
  presets/api.go
  presets/field.go
  presets/model.go
  presets/nested_many.go
  presets/plugin.go
  publish/version_listener.go
Labels: size/M

#303 update microsite and add file.Close()
  example/admin/input_demo_config.go
  media/base/upload.go
  microsite/config.go
  microsite/microsite.go
Labels: size/S

#304 fix preview url when online;fix no config demo contianer
  example/admin/perm.go
  example/admin/user_config.go
  go.mod
  go.sum
  pagebuilder/builder.go
  pagebuilder/content.go
  pagebuilder/editor.go
  pagebuilder/model.go
  pagebuilder/settings.go
  publish/builder.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/M

#308 fix row auto save
  cmd/qor5/website-template/admin/integration_test.go
  example/integration/pagebuilder_test.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  presets/listeditor.go
  presets/listener.go
Labels: size/M

#307 Fix crop
  media/cropper.go
  media/media_box.go
  publish/builder.go
Labels: size/S

#311 Fix l10n
  docs/docsrc/examples/examples_admin/localization.go
  docs/docsrc/examples/examples_admin/localization_test.go
  example/admin/config.go
  l10n/builder.go
  l10n/config.go
  l10n/events.go
  l10n/img.go
  media/cropper.go
  pagebuilder/builder.go
  pagebuilder/model.go
  seo/admin_test.go
Labels: size/L

#313 feat: change confirmation dialog ok to @click
  presets/presets.go
Labels: size/XS

#314 detailing actions
  docs/docsrc/examples/examples_presets/detailing.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  presets/detailing.go
  presets/listing_compo.go
Labels: size/L

#317 upgrade x;fix detail layout;change crop card to height
  example/integration/pagebuilder_test.go
  go.mod
  go.sum
  media/cropper.go
  pagebuilder/settings.go
  seo/admin.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/S

#318 activityx
  activity/README.md
  activity/activity_log.go
  activity/activity_user.go
  activity/admin.go
  activity/builder.go
  activity/builder_test.go
  activity/log_diff.go
  activity/log_diff_test.go
  activity/log_helpers.go
  activity/messages.go
  activity/model_builder.go
  activity/note.go
  activity/note_actions.go
  activity/timeline.go
  activity/util.go
  activity/util_test.go
  cmd/qor5/website-template/admin/config.go
  docs/docsrc/examples/examples_admin/activity.go
  docs/docsrc/examples/examples_admin/activity_test.go
  docs/docsrc/examples/examples_admin/publish.go
  docs/docsrc/examples/examples_admin/publish_test/flow_delete_version_test.go
  docs/docsrc/examples/examples_admin/publish_test/helper_test.go
  example/admin/auth.go
  example/admin/config.go
  example/admin/note.go
  example/admin/perm.go
  example/admin/user_config.go
  go.mod
  go.sum
  l10n/events.go
  pagebuilder/builder.go
  presets/actions/const.go
  presets/context.go
  presets/detailing.go
  presets/examples/setup.go
  presets/listing_builder.go
  presets/listing_compo.go
  presets/model.go
  presets/presets.go
  presets/section.go
  publish/builder.go
  publish/event.go
  publish/interfaces.go
  publish/publish_event.go
  publish/version_compo.go
  seo/model.go
  worker/action_job.go
  worker/builder.go
Labels: size/XXL

#319 publish perm
  presets/const.go
  presets/listing_compo.go
  publish/perm.go
  publish/publish_event.go
  publish/schedule_event.go
  publish/version_compo.go
  publish/version_event.go
Labels: size/L

#320 NewTimelineCompo and ParentSizeObserver
  activity/messages.go
  activity/model_builder.go
  activity/timeline.go
  docs/docsrc/examples/examples_admin/activity.go
  example/admin/perm.go
  go.mod
  go.sum
  presets/common_page.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/L

#322 fix user role
  example/admin/user_config.go
  role/builder.go
Labels: size/M

#323 pagebuilder detail preview thin;add activity;change html tag to vx;ch…
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  example/integration/pagebuilder_test.go
  go.mod
  go.sum
  pagebuilder/builder.go
  pagebuilder/content.go
  pagebuilder/editor.go
  pagebuilder/model.go
  pagebuilder/settings.go
Labels: size/L

#324 Fix pagetitle
  pagebuilder/builder.go
  pagebuilder/settings.go
  presets/presets.go
Labels: size/L

#326 fix activity_logs demo bug
  example/admin/config.go
Labels: size/S

#328 simple fix configPost display and select dialog demo
  activity/model_builder.go
  example/admin/config.go
  example/admin/input_demo_config.go
  publish/builder.go
  publish/version_compo.go
  publish/version_listener.go
Labels: size/L

#329 listing fix and improve
  example/admin/profile.go
  presets/listing_compo.go
Labels: size/M

#330 fix doLocalizeTo without new id;fix left drawer fixed
  l10n/events.go
  presets/presets.go
Labels: size/M

#333 fix gorm import
  activity/model_builder.go
  go.sum
Labels: size/XS

#334 listing title func
  activity/admin.go
  docs/docsrc/examples/examples_admin/publish_test/helper_test.go
  example/admin/messages.go
  pagebuilder/builder.go
  presets/listing_builder.go
  presets/nested_many.go
  publish/version_compo.go
Labels: size/L

#335 fix template detail error; fix pagebuilder displayName auto warp on s…
  example/integration/pagebuilder_test.go
  pagebuilder/builder.go
  pagebuilder/model.go
Labels: size/S

#336 fix preview iframe unvisible full
  pagebuilder/settings.go
Labels: size/XS

#337 fix displayname maxwidth
  pagebuilder/model.go
Labels: size/XS

#339 listing: trigger reload if click search icon
  presets/listing_compo.go
Labels: size/M

#332 feat: Add section update permission
  example/integration/perm_test.go
  presets/detailing.go
  presets/section.go
Labels: size/L

#340 fixed dialog height
  media/cropper.go
Labels: size/XS

#342 remove img param
  media/cropper.go
Labels: size/XS

#344 upgrade cropper in x
  go.mod
  go.sum
Labels: size/XS

#346 upgrade x;fix editor-bar title max width
  go.mod
  go.sum
  pagebuilder/model.go
Labels: size/XS

#348 simplify gitignore && add missing test file
  .gitignore
  docs/docsrc/examples/examples_admin/publish_test/flow_perm_test.go
Labels: size/XL

#349 fix keyword missed unescape && revert to page 0 after state changed
  docs/docsrc/examples/examples_presets/listing.go
  go.mod
  go.sum
  presets/listing_compo.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/M

#350 fix add container;fixed width for editor bar
  pagebuilder/model.go
Labels: size/XS

#351 add idea
  .gitignore
Labels: size/XS

#352 listing add DisplayColumnsProcessor
  activity/model_builder.go
  activity/util.go
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  presets/listing_builder.go
  presets/listing_compo.go
  presets/nested_many.go
  presets/utils.go
Labels: size/L

#353 ensure creating reuse editing callbacks, unless Wrap is not used
  activity/admin.go
  presets/editing.go
  publish/builder.go
Labels: size/M

#355 Feat: perm without id
  docs/docsrc/examples/examples_presets/perm_role_test.go
  presets/field.go
  presets/nested_many.go
Labels: size/L

#356 Fix: version dialog perm wrong
  docs/docsrc/examples/examples_admin/publish.go
  docs/docsrc/examples/examples_admin/publish_test.go
  publish/version_compo.go
Labels: size/S

#357 fix online url clipboard
  pagebuilder/settings.go
Labels: size/XS

#359 fix displayname l18n translate
  pagebuilder/model.go
Labels: size/S

#360 activity: support multitenant
  activity/README.md
  activity/activity_log.go
  activity/admin.go
  activity/builder.go
  activity/builder_test.go
  activity/messages.go
  activity/model_builder.go
  activity/note.go
  activity/tests/gorm_test.go
  activity/timeline.go
  activity/util.go
  activity/util_test.go
  cmd/qor5/website-template/admin/config.go
  docs/docsrc/examples/examples_admin/activity.go
  docs/docsrc/examples/examples_admin/activity_test.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/publish.go
  example/admin/config.go
  example/admin/perm.go
  example/admin/profile.go
  example/admin/user_config.go
Labels: size/XXL

#361 presets: fix listing title jp message
  presets/messages.go
Labels: size/XS

#362 Fix category
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  pagebuilder/builder.go
Labels: size/M

#363 Section validator only show GlobalError
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/mux.go
  presets/section.go
Labels: size/M

#364 List Section validator only show GlobalError
  presets/section.go
Labels: size/XS

#365 presets: ensure that zero value is recognized as empty
  presets/utils.go
  presets/utils_test.go
Labels: size/M

#366 Set editing error message timeout 2000
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/editing.go
  docs/docsrc/examples/examples_presets/editing_test.go
  docs/docsrc/examples/examples_presets/mux.go
  presets/editing.go
Labels: size/M

#367 listing: WrapDisplayColumns and CustomizeTableHead
  docs/docsrc/examples/examples_admin/publish_test/helper_test.go
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/listing.go
  docs/docsrc/examples/examples_presets/listing_test.go
  presets/listing_builder.go
  presets/listing_compo.go
Labels: size/L

#368 Feat media
  example/integration/media_test.go
  go.mod
  go.sum
  media/cropper.go
  media/events.go
  media/filechooser.go
  media/integration/integration_test.go
  media/list.go
  media/media_box.go
  media/media_library/media_library.go
  media/names.go
  pagebuilder/model.go
Labels: size/XXL

#369 Feat: Support section disable label
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/mux.go
  presets/section.go
Labels: size/M

#372 activity/publish: internal handling of i18n && detailing: fix title i18n
  activity/admin.go
  activity/messages.go
  activity/model_builder.go
  activity/timeline.go
  activity/util.go
  docs/docsrc/examples/examples_admin/activity.go
  docs/docsrc/examples/examples_admin/activity_test.go
  docs/docsrc/examples/examples_admin/publish_test/helper_test.go
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/listing.go
  docs/docsrc/examples/examples_presets/listing_test.go
  example/admin/messages.go
  presets/context.go
  presets/detailing.go
  presets/editing.go
  presets/listing_builder.go
  presets/listing_compo.go
  presets/model.go
  presets/nested_many.go
  presets/presets.go
  publish/builder.go
  publish/messages.go
  publish/version_compo.go
  seo/admin.go
Labels: size/XL

#373 container only one add button;fix zero catogory; media library db def…
  docs/docsrc/examples/examples_vuetifyx/auto-complete.go
  docs/docsrc/examples/examples_vuetifyx/mux.go
  go.mod
  go.sum
  media/integration/integration_test.go
  media/media_box.go
  media/media_library/media_library.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/model.go
Labels: size/M

#374 presets: merge query when change language
  presets/presets.go
Labels: size/XS

#376 feat: Rename section ValidateFunc
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  presets/section.go
Labels: size/XS

#380 fix: 🐛 fix menu scrolling problem
  presets/presets.go
Labels: size/XS

#379 remove pagetitleFunc;fix pagebuilder media title
  media/filechooser.go
  media/list.go
  pagebuilder/builder.go
  presets/context.go
  presets/detailing.go
  presets/listing_builder.go
  presets/presets.go
Labels: size/L

#382 fix rename
  example/integration/media_test.go
  media/filechooser.go
  media/media_box.go
Labels: size/S

#384 fix copy;folder rename;rename disable
  example/integration/media_test.go
  media/media_box.go
Labels: size/M

#386 fix publish reactive
  activity/timeline.go
  docs/docsrc/examples/examples_admin/publish_test/flow_publish_test.go
  docs/docsrc/examples/examples_presets/detailing.go
  l10n/events.go
  presets/detailing.go
  presets/editing.go
  presets/examples/setup.go
  presets/listener.go
  publish/messages.go
  publish/publish_event.go
  publish/schedule_event.go
  publish/version_compo.go
  publish/version_event.go
  publish/version_listener.go
Labels: size/L

#387 Fix empty
  example/integration/pagebuilder_test.go
  go.mod
  go.sum
  media/filechooser.go
  media/media_box.go
  pagebuilder/builder.go
  pagebuilder/helper.go
Labels: size/L
