Repository qor5/admin, pull requests merged in 2024-08, with the labels that each got.

#388 media: Support media_box with simple img URL
  docs/docsrc/examples/examples_admin/media.go
  docs/docsrc/examples/examples_admin/media_test.go
  docs/docsrc/examples/examples_admin/mux.go
  media/media_box.go
  media/media_library/media_box.go
Labels: size/L

#389 Upgrade web@v3.0.5, x@v3.0.6 and other deps
  go.mod
  go.sum
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/L

#391 style: UI improvement of "add New" Button、menu layout, v-main layout
  presets/listing_compo.go
  presets/messages.go
  presets/presets.go
Labels: size/S

#394 Upgrade docker golang to latest
  docs/Dockerfile
  example/Dockerfile
  example/cmd/data-resetor/Dockerfile
  example/cmd/publisher/Dockerfile
Labels: size/XS

#395 chore: update version of qor5/x
  go.mod
  go.sum
Labels: size/XS

#397 image preview
  media/filechooser.go
Labels: size/XS

#400 fix: menu-bar language area too narrow
  presets/presets.go
Labels: size/XS

#401 fix filename show readonly
  media/filechooser.go
Labels: size/XS

#404 fix upload ;and move to dialog next folder
  media/filechooser.go
  media/media_box.go
Labels: size/XS

#403 Support field section title i18n
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  presets/field.go
Labels: size/S

#407 login: profile builder && session builder
  activity/README.md
  activity/admin.go
  activity/builder.go
  activity/builder_test.go
  activity/messages.go
  activity/model_builder.go
  activity/note.go
  activity/util.go
  example/admin/auth.go
  example/admin/config.go
  example/admin/messages.go
  example/admin/middlewares.go
  example/admin/profile.go
  example/admin/router.go
  example/admin/session_mgmt.go
  example/admin/user_config.go
  example/integration/profile_test.go
  example/main.go
  example/models/login_session.go
  example/models/user.go
  go.mod
  go.sum
  login/messages.go
  login/profile.go
  login/session.go
  login/util.go
  login/views.go
Labels: size/XXL

#406 update translations
  activity/messages.go
  docs/docsrc/examples/examples_admin/activity_test.go
  go.mod
  go.sum
  l10n/messages.go
  presets/messages.go
Labels: size/M

#409 Fix move
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  media/cropper.go
  media/filechooser.go
  media/media_box.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/model.go
  pagebuilder/settings.go
  presets/detailing.go
  presets/presets.go
  presets/section.go
Labels: size/L

#408 Add more section label i18n test
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
Labels: size/S

#410 rename Categories to Page Categories
  pagebuilder/builder.go
Labels: size/XS

#412 fix page new label
  pagebuilder/builder.go
Labels: size/XS

#413 fix next folder error
  media/media_box.go
Labels: size/XS

#415 Feat UI reborn
  presets/listing_compo.go
  presets/presets.go
Labels: size/M

#416 fix search click clear
  media/filechooser.go
Labels: size/XS

#417 test
  media/filechooser.go
Labels: size/M

#418 style: adjusting position of pagination
  activity/timeline.go
  pagebuilder/settings.go
  presets/common_page.go
  presets/detailing.go
  presets/listing_builder.go
  presets/listing_compo.go
  publish/version_compo.go
Labels: size/M

#419 chore: update the dependency of qor5/x/v3
  go.mod
  go.sum
  presets/detailing.go
Labels: size/XS

#420 feat: custimize ok/cancel button text for confirmation dialog
  presets/presets.go
Labels: size/S

#422 fix: adjust activity gap when width less than 900
  presets/common_page.go
Labels: size/XS

#421 Fix media
  example/admin/router.go
  example/integration/l18n_test.go
  login/session.go
  media/filechooser.go
  media/list.go
  media/media_box.go
  pagebuilder/builder.go
  pagebuilder/model.go
  pagebuilder/settings.go
Labels: size/L

#423 fix: section label i18n wrong
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  go.sum
  presets/section.go
Labels: size/S

#424 test
  activity/timeline.go
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  example/admin/router.go
  example/integration/l18n_test.go
  go.mod
  go.sum
  login/session.go
  media/filechooser.go
  media/list.go
  media/media_box.go
  pagebuilder/builder.go
  pagebuilder/model.go
  pagebuilder/settings.go
  presets/common_page.go
  presets/detailing.go
  presets/listing_builder.go
  presets/listing_compo.go
  presets/presets.go
  presets/section.go
  publish/version_compo.go
Labels: size/L

#425 section: support cancel section, add button i18n in section
  docs/docsrc/examples/examples_presets/detailing_test.go
  go.mod
  go.sum
  presets/detailing.go
  presets/messages.go
  presets/section.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/L

#426 Fix l18n
  cmd/qor5/website-template/admin/messages.go
  example/admin/messages.go
  media/filechooser.go
  media/media_box.go
  media/messages.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/helper.go
  pagebuilder/messages.go
  pagebuilder/model.go
  pagebuilder/settings.go
Labels: size/L

#427 fix: Add i18n key
  presets/messages.go
  publish/messages.go
Labels: size/XS

#428 fix: Add add row i18n
  presets/section.go
Labels: size/XS

#430 fix: KAK-3200
  pagebuilder/settings.go
  presets/presets.go
Labels: size/XS

#429 presets: add MenuItem method for ModelBuilder
  docs/docsrc/examples/examples_presets/menu.go
  docs/docsrc/examples/examples_presets/menu_test.go
  docs/docsrc/examples/examples_presets/mux.go
  presets/model.go
  presets/presets.go
Labels: size/L

#431 listing: use new VXTablePagination
  go.mod
  go.sum
  presets/listing_compo.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/M

#433 fix change language icon no change;change media choose click event area
  example/integration/media_test.go
  media/events.go
  media/filechooser.go
  media/media_box.go
  presets/icons.go
  presets/integration/language_test.go
  presets/presets.go
Labels: size/L

#434 profile optional
  docs/docsrc/examples/examples_admin/mux.go
  docs/docsrc/examples/examples_admin/profile.go
  docs/docsrc/examples/examples_admin/profile_test.go
  example/admin/config.go
  login/profile.go
  login/util.go
Labels: size/L

#437 admin: modify i18n JP
  pagebuilder/messages.go
  presets/messages.go
  publish/messages.go
Labels: size/L

#436 style: 💄 adjusting gap of main layout and detail page
  presets/common_page.go
  presets/listing_compo.go
  presets/nested_many.go
  presets/section.go
Labels: size/M

#438 fix page message
  example/admin/messages.go
Labels: size/XS

#439 fix move container
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/messages.go
  pagebuilder/model.go
Labels: size/M

#440 profile: add CustomizeButtons
  docs/docsrc/examples/examples_admin/profile.go
  docs/docsrc/examples/examples_admin/profile_test.go
  login/profile.go
Labels: size/M

#443 chore: update version of x
  go.mod
  go.sum
Labels: size/XS

#442 presets: add HumanizeTime i118n keys
  presets/messages.go
  presets/messages_test.go
Labels: size/L

#444 fix media search file to filename
  example/integration/media_test.go
  media/filechooser.go
  pagebuilder/messages.go
Labels: size/S

#446 admin: Modify JP translation
  activity/messages.go
  login/messages.go
  media/messages.go
  pagebuilder/messages.go
  presets/messages.go
  publish/messages.go
Labels: size/L

#445 use presets.Message.HumanizeTime
  activity/admin.go
  activity/timeline.go
  docs/docsrc/examples/examples_admin/activity_test.go
  login/session.go
  presets/messages.go
Labels: size/L

#447 Feat autocomplete
  autocomplete/builder.go
  autocomplete/integration/autocomplete_test.go
  autocomplete/model.go
  docs/docsrc/examples/examples_admin/autocomplete.go
  docs/docsrc/examples/examples_admin/mux.go
  docs/docsrc/examples/examples_admin/server/main.go
  docs/docsrc/examples/examples_vuetifyx/auto-complete.go
  docs/docsrc/examples/utils.go
  go.mod
  go.sum
  media/list.go
  media/messages.go
  pagebuilder/model.go
  presets/autocomplete_data_source.go
Labels: size/XL

#449 i18n: Modify New i18n
  presets/messages.go
Labels: size/XS

#450 pagebuilder: builtin i18n
  example/integration/pagebuilder_test.go
  pagebuilder/builder.go
  pagebuilder/messages.go
  publish/version_compo.go
Labels: size/L

#451 upgrade x;fix page detail 0 value; RenderInput add Obj
  example/integration/pagebuilder_test.go
  go.mod
  go.sum
  media/cropper.go
  pagebuilder/builder.go
  pagebuilder/model.go
  pagebuilder/settings.go
Labels: size/M

#452 fix container name i18n
  example/admin/messages.go
  go.mod
  go.sum
  pagebuilder/builder.go
  pagebuilder/model.go
Labels: size/M

#453 i18n: listeditor && version && pagebuilder
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  docs/docsrc/examples/examples_admin/publish_test.go
  pagebuilder/builder.go
  pagebuilder/messages.go
  pagebuilder/model.go
  presets/listeditor.go
  publish/version_event.go
Labels: size/M

#455 only page container can config
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  pagebuilder/builder.go
  pagebuilder/model.go
Labels: size/L

#456 feat: add extra menu icon to support kakuyasu(cs/cms)admin
  presets/presets.go
Labels: size/S

#457 presets: bypass assets in notFoundHandler
  autocomplete/builder.go
  docs/docsrc/examples/examples_presets/presets_test.go
  presets/presets.go
Labels: size/M

#458 fix selectItem;
  docs/docsrc/examples/examples_admin/autocomplete.go
  docs/docsrc/examples/examples_admin/autocomplete_test.go
  go.mod
  go.sum
Labels: size/M

#459 profile: fix ui && add PrependCompos
  docs/docsrc/examples/examples_admin/profile_test.go
  login/profile.go
  presets/listing_compo.go
Labels: size/L

#460 pagebuilder: i18n
  pagebuilder/messages.go
Labels: size/XS

#461 activity: fix "Long content coverage button" KAK-3917
  activity/timeline.go
  go.mod
  go.sum
Labels: size/M

#462 fix no files show page;search icon no click event
  media/filechooser.go
Labels: size/M

#464 Feat UI reborn
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/perm_role_test.go
  presets/detailing.go
  presets/field.go
  presets/field_defaults.go
  presets/integration/fields_test.go
  presets/presets.go
  presets/section.go
Labels: size/L

#465 upgrade x
  go.mod
  go.sum
Labels: size/XS

#466 add device disabled,fix editor bar css
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  pagebuilder/builder.go
  pagebuilder/messages.go
  pagebuilder/model.go
Labels: size/M

#467 listing: auto scroll to top after reload
  docs/docsrc/examples/examples_admin/server/main.go
  example/main.go
  presets/listing_compo.go
Labels: size/M

#469 fix: add persistent and noClickAnimation to change password dialog
  login/views.go
Labels: size/XS

#470 listing: fix pagination jitter and add PaginationTotalVisible method
  docs/docsrc/examples/examples_admin/listing.go
  docs/docsrc/examples/examples_admin/listing_test.go
  go.mod
  go.sum
  presets/listing_builder.go
  presets/listing_compo.go
Labels: size/L

#471 listing: textFieldSearch: reload only if keyword actually changed
  presets/listing_compo.go
Labels: size/M

#472 editing: toast msgr.SuccessfullyCreated when created && some i18n
  activity/messages.go
  example/admin/messages.go
  pagebuilder/messages.go
  presets/editing.go
  presets/messages.go
Labels: size/M

#473 Feat UI reborn
  presets/icons.go
  presets/listing_compo.go
  presets/section.go
Labels: size/M

#474 login: use x/login wrap methods
  example/admin/auth.go
  go.mod
  go.sum
  login/example/main.go
  login/session.go
Labels: size/L

#476 presets: DeleteConfirmationText i18n (KAK-3552/KAK-3553)
  media/media_box.go
  presets/listing_builder.go
  presets/messages.go
Labels: size/L

#477 Fix: default field will reset setterFunc
  docs/docsrc/examples/examples_presets/editing.go
  docs/docsrc/examples/examples_presets/editing_test.go
  docs/docsrc/examples/examples_presets/mux.go
  presets/field.go
Labels: size/M

#478 chore: fix the changes with combine of vuetify + vuetifyx
  docs/docsrc/examples/examples_vuetify/mux.go
  docs/docsrc/examples/examples_vuetifyx/mux.go
  go.mod
  go.sum
  presets/presets.go
Labels: size/S

#480 Qor5 cleanup
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/server/main.go
  example/main.go
  hack/build-deploy-app.sh
  login/views.go
  pagebuilder/builder.go
  pagebuilder/messages.go
  pagebuilder/model.go
  plantbuild/build.jsonnet
  plantbuild/images.jsonnet
  presets/listing_compo.go
Labels: size/M

#475 login: add missing next middleware calls
  login/session.go
Labels: size/S

#481 login: change password ux
  docs/docsrc/examples/examples_admin/login.go
  docs/docsrc/examples/examples_admin/login_test.go
  docs/docsrc/examples/examples_admin/mux.go
  go.mod
  go.sum
  login/builder.go
  login/view_common.go
  login/views.go
  presets/messages.go
  presets/utils.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/L

#479 remove example ci/cd
  hack/build-deploy-app.sh
  plantbuild/build.jsonnet
  plantbuild/images.jsonnet
Labels: size/XS

#482 fix image ALLOW_TYPE don`t show folders
  example/integration/media_test.go
  go.mod
  go.sum
  l10n/config.go
  media/events.go
  media/filechooser.go
  pagebuilder/model.go
  presets/listing_compo.go
Labels: size/L

#483 vue-i18n && NewLiveFilterItem && pagebuilder history.back && pagebuilder i18n
  example/admin/config.go
  go.mod
  go.sum
  pagebuilder/builder.go
  pagebuilder/messages.go
  pagebuilder/model.go
  presets/presets.go
  publish/utils.go
Labels: size/M

#484 Fix example post edit body wrong
  example/admin/config.go
  example/integration/post_test.go
Labels: size/M

#485 media add wrap saver
  docs/docsrc/examples/examples_admin/media.go
  docs/docsrc/examples/examples_admin/media_test.go
  media/base/upload.go
  media/builder.go
  media/cropper.go
  media/filechooser.go
  media/integration/integration_test.go
  media/media_box.go
Labels: size/L

#487 fix field builder clone
  example/integration/media_test.go
  presets/field.go
Labels: size/XS

#488 Support listing button label i18n
  docs/docsrc/examples/examples_presets/listing.go
  docs/docsrc/examples/examples_presets/listing_test.go
  docs/docsrc/examples/examples_presets/messages.go
  presets/listing_compo.go
Labels: size/M

#489 profile: add optional rename callback && WrapSubtitleCompo
  docs/docsrc/examples/examples_admin/profile_test.go
  example/integration/profile_test.go
  login/profile.go
Labels: size/L

#486 Fix section duplicate portal
  presets/section.go
Labels: size/S

#490 pagebuilder add DisabledNormalContainersGroup
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  pagebuilder/builder.go
  pagebuilder/model.go
Labels: size/L

#491 add URLNoCached
  media/base/base.go
  media/integration/integration_test.go
  media/media_library/media_box.go
Labels: size/S

#492 Fix cancel edit display wrong section title
  docs/docsrc/examples/examples_presets/detailing_test.go
  presets/section.go
Labels: size/S

#493 fix media choose file select
  example/integration/media_test.go
  media/filechooser.go
  media/media_box.go
Labels: size/L

#496 listing: refactor current active && publish: keep current active item style
  go.mod
  go.sum
  login/views.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  presets/detailing.go
  presets/editing.go
  presets/listing_builder.go
  presets/listing_compo.go
  presets/presets.go
  publish/builder.go
  publish/version_compo.go
  publish/version_listener.go
Labels: size/L

#495 Fix delete version message JP wrong
  publish/messages.go
Labels: size/XS

#494 upgrade x
  go.mod
  go.sum
Labels: size/XS

#497 add change drawer data can`t close direct
  docs/docsrc/examples/examples_admin/publish_test/flow_duplicate_test.go
  docs/docsrc/examples/examples_admin/publish_test/flow_new_test.go
  docs/docsrc/examples/examples_admin/publish_test/flow_perm_test.go
  docs/docsrc/examples/examples_admin/publish_test/flow_publish_test.go
  docs/docsrc/examples/examples_admin/publish_test/flow_schedule_test.go
  pagebuilder/settings.go
  presets/const.go
  presets/detailing.go
  presets/editing.go
  presets/integration/example_test.go
  presets/presets.go
  presets/section.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/M

#498 add missing Clear i18n for datepicker
  presets/messages.go
Labels: size/XS

#499 fix update js error
  pagebuilder/editor.go
Labels: size/XS

#500 fix media choose file can`t enter folder;rename confirm
  docs/docsrc/examples/examples_admin/publish_test/flow_duplicate_test.go
  docs/docsrc/examples/examples_admin/publish_test/flow_new_test.go
  docs/docsrc/examples/examples_admin/publish_test/flow_perm_test.go
  docs/docsrc/examples/examples_admin/publish_test/flow_publish_test.go
  docs/docsrc/examples/examples_admin/publish_test/flow_schedule_test.go
  media/filechooser.go
  media/media_box.go
  pagebuilder/editor.go
  presets/const.go
  presets/detailing.go
  presets/editing.go
  presets/presets.go
  presets/section.go
Labels: size/M

#501 Feat UI reborn
  presets/presets.go
Labels: size/M

#502 fix doupdate use confirm script
  presets/detailing.go
  presets/editing.go
  presets/presets.go
  publish/version_listener.go
Labels: size/XS

#503 feat: support progressBar drived by isReloadingPage param
  go.mod
  go.sum
  presets/presets.go
Labels: size/XS

#504 fix media button sucking
  go.mod
  go.sum
  media/filechooser.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/S

#505 upgrade x
  .github/codecov.yml
  docs/docs/basics/filter.html
  docs/docs/search_indexes.json
  docs/docsrc/examples/examples_presets/filter.go
  go.mod
  go.sum
Labels: size/S

#506 Feat UI reborn
  media/filechooser.go
  presets/detailing.go
  presets/editing.go
  presets/listing_compo.go
  publish/version_compo.go
Labels: size/S

#509 no url set cached url empty string
  media/base/base.go
  media/integration/integration_test.go
  media/media_library/media_box.go
Labels: size/S

#510 back-btn: determine whether to go back based on history.last
  go.mod
  go.sum
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/models.go
  presets/presets.go
Labels: size/M

#508 style: confirm dialog adjusting
  go.mod
  go.sum
  login/views.go
  presets/presets.go
Labels: size/M

#512 publish: support customize StatusXXX
  docs/docsrc/examples/examples_presets/filter.go
  docs/docsrc/examples/examples_presets/filter_test.go
  publish/builder.go
  publish/version_compo.go
Labels: size/M

#511 section: list section add row no longer save direct
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  docs/docsrc/examples/examples_admin/seo_test.go
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/mux.go
  docs/docsrc/examples/examples_presets/perm_role_test.go
  example/integration/pagebuilder_test.go
  example/integration/post_test.go
  presets/detailing.go
  presets/integration/section_test.go
  presets/section.go
Labels: size/XL

#514 activity: exclusive editing && confirmation of leaving during editing
  activity/timeline.go
  go.mod
  go.sum
  presets/presets.go
Labels: size/M

#516 activity: add FindLogsForTimelineFunc
  activity/builder.go
  activity/timeline.go
  docs/docsrc/examples/examples_admin/activity.go
  docs/docsrc/examples/examples_admin/activity_test.go
  publish/interfaces.go
Labels: size/M

#515 style: adjusting of list-page layout
  presets/listing_compo.go
Labels: size/XS

#517 change media library layout;add perm
  docs/docsrc/examples/examples_admin/media.go
  docs/docsrc/examples/examples_admin/media_test.go
  example/admin/perm.go
  example/integration/media_test.go
  media/filechooser.go
  media/media_box.go
  media/perm.go
  media/svg.go
Labels: size/XL

#519 Feat UI reborn
  go.mod
  go.sum
  presets/detailing.go
  presets/listing_compo.go
  presets/nested_many.go
Labels: size/S

#518 activity: add `scope` field to `activity_logs` to handle complex queries
  activity/activity_log.go
  activity/builder_test.go
  activity/model_builder.go
  activity/note.go
  activity/note_test.go
  activity/tests/gorm_test.go
  docs/docsrc/examples/examples_admin/activity_test.go
Labels: size/L

#520 fix mediabox dialog title
  media/filechooser.go
Labels: size/XS

#521 section: fix vue warn caused by a unused v-bind
  presets/section.go
Labels: size/XS

#523 fix move to just push
  example/integration/media_test.go
  media/filechooser.go
  media/media_box.go
Labels: size/M

#522 presets: fix dialog scroll for detailing and editing
  presets/presets.go
Labels: size/XS

#524 publish: disable button on editing && activity: reset data changed on mounted
  activity/timeline.go
  presets/const.go
  publish/version_compo.go
  publish/version_listener.go
Labels: size/M

#525 Fix section list create wrong with nil value
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  presets/section.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/M

#526 singleton: fix editing param id
  docs/docsrc/examples/examples_admin/mux.go
  docs/docsrc/examples/examples_admin/singleton.go
  docs/docsrc/examples/examples_admin/singleton_test.go
  go.mod
  go.sum
  presets/editing.go
Labels: size/L

#527 activity: fix missing diff for Version.VersionName
  activity/builder.go
  activity/util.go
  activity/util_test.go
Labels: size/L

#530 detailing: fix missing do action permission check
  docs/docsrc/examples/examples_admin/listing.go
  docs/docsrc/examples/examples_admin/listing_test.go
  docs/docsrc/examples/examples_admin/singleton.go
  docs/docsrc/examples/examples_presets/detailing.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/perm_role_test.go
  presets/detailing.go
  presets/listing_compo.go
Labels: size/XL

#531 presets: add LookUpModelBuilder and tests
  presets/presets.go
  presets/presets_test.go
  publish/version_compo.go
Labels: size/M

#532 publish: use OrderBy method for version list dialog
  publish/version_compo.go
Labels: size/XS

#535 Feat UI reborn
  go.mod
  go.sum
  presets/listing_compo.go
Labels: size/XS

#533 fix: pagebuilder i18n
  pagebuilder/messages.go
Labels: size/XS

#534 activity: new ui and ux
  activity/README.md
  activity/builder.go
  activity/timeline.go
  go.mod
  go.sum
Labels: size/L

#536 upgrade `x/v3 v3.0.8`
  go.mod
  go.sum
Labels: size/S

#537 activity: add ContextWithDB and tests
  activity/builder_test.go
  activity/model_builder.go
Labels: size/M

#538 pagebuilder with template
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  example/integration/pagebuilder_template_test.go
  example/integration/pagebuilder_test.go
  media/filechooser.go
  media/list.go
  pagebuilder/builder.go
  pagebuilder/content.go
  pagebuilder/editor.go
  pagebuilder/messages.go
  pagebuilder/model.go
  pagebuilder/model_events.go
  pagebuilder/models.go
  pagebuilder/page.go
  pagebuilder/settings.go
  pagebuilder/template.go
  pagebuilder/template_events.go
Labels: size/XXL

#539 fix string format
  media/filechooser.go
  pagebuilder/builder.go
  pagebuilder/model_events.go
  pagebuilder/settings.go
  pagebuilder/template.go
Labels: size/S
