Repository qor5/admin, pull requests merged in 2024-11, with the labels that each got.

#695 fix page detail slug CategoryID to VFieldError
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  example/admin/config.go
  pagebuilder/example/containers/heading.go
  pagebuilder/example/containers/list_content_lite.go
  pagebuilder/example/containers/tag.go
  pagebuilder/settings.go
Labels: size/M

#699 fix Items Validate Failed Error Show;fix localizeMenu existLocals
  example/integration/pagebuilder_test.go
  l10n/config.go
  pagebuilder/builder.go
  pagebuilder/example/containers/in_numbers.go
  presets/editing.go
  presets/section.go
Labels: size/M

#706 fix: https://theplanttokyo.atlassian.net/browse/QOR5-514
  presets/editing.go
Labels: size/XS

#712 Feat validate
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_presets/perm_role_test.go
  example/admin/config.go
  example/admin/demo_case.go
  example/integration/demo_case_test.go
  example/integration/pagebuilder_test.go
  go.mod
  go.sum
  l10n/config.go
  pagebuilder/builder.go
  pagebuilder/example/containers/heading.go
  pagebuilder/example/containers/in_numbers.go
  pagebuilder/example/containers/list_content_lite.go
  pagebuilder/example/containers/tag.go
  pagebuilder/helper.go
  pagebuilder/messages.go
  pagebuilder/page.go
  pagebuilder/settings.go
  presets/actions/const.go
  presets/api.go
  presets/const.go
  presets/detailing.go
  presets/editing.go
  presets/field.go
  presets/field_defaults.go
  presets/integration/example_test.go
  presets/integration/fields_test.go
  presets/listeditor.go
  presets/listener.go
  presets/listing_builder.go
  presets/listing_compo.go
  presets/model.go
  presets/section.go
  presets/utils.go
Labels: size/XXL

#722 fix: the wrapper border size not accurate
  pagebuilder/editor.go
  pagebuilder/model.go
Labels: size/XS

#728 loadImageCropper First to Find
  media/cropper.go
Labels: size/S

#730 fix: the wrapper border size not accurate
  pagebuilder/editor.go
  pagebuilder/model.go
  presets/editing.go
Labels: size/S

#732 media MoveTo Add Activity
  media/media_box.go
Labels: size/S

#734 fix: oversize right drawer init width and resize case
  pagebuilder/editor.go
Labels: size/S

#698 listing: add i18n labels for datarange filters
  go.mod
  go.sum
  presets/listing_compo.go
  presets/messages.go
Labels: size/S

#697 text-wrap for pre element
  activity/admin.go
  activity/timeline.go
  publish/status_compo.go
Labels: size/XS

#720 tiptap: fix redirect to /extra/github.css.map after login
  tiptap/embed/github.css
Labels: size/L

#736 Fix wrapevent
  example/admin/config.go
  example/admin/demo_case.go
  example/admin/seo.go
  example/integration/pagebuilder_online_test.go
  example/integration/pagebuilder_test.go
  login/profile.go
  media/base/upload.go
  media/builder.go
  media/cropper.go
  media/filechooser.go
  media/media_box.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/example/config.go
  pagebuilder/messages.go
  pagebuilder/model.go
  pagebuilder/model_events.go
  pagebuilder/page.go
  pagebuilder/settings.go
  pagebuilder/template.go
  presets/editing.go
  presets/field_defaults.go
  presets/integration/fields_test.go
  presets/messages.go
  presets/section.go
  publish/messages.go
  publish/version_compo.go
  seo/admin.go
  seo/builder.go
  seo/model.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/XL

#703 activity: nowrap for FieldName columns
  activity/admin.go
  docs/docsrc/examples/examples_admin/activity_test.go
Labels: size/M

#696 publish: add WithScheduleRecordsFinder
  publish/publish_test.go
  publish/schedule_publish_builder.go
Labels: size/L

#738 Feat daniel
  docs/docsrc/examples/examples_admin/activity_test.go
  example/admin/config.go
  example/admin/seo.go
  go.mod
  go.sum
  media/builder.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/page.go
  presets/editing.go
  seo/admin.go
  seo/builder.go
  seo/model.go
Labels: size/XL

#747 Feat daniel UI
  example/admin/demo_case.go
  go.mod
  go.sum
  media/filechooser.go
Labels: size/L

#685 Login screen
  example/admin/auth.go
  example/admin/config.go
  example/admin/login_views.go
  example/admin/router.go
  example/integration/l18n_test.go
  example/integration/login_test.go
  go.mod
  go.sum
  login/embed/defaultLeftImage.jpg
  login/messages.go
  login/view_common.go
  login/views.go
  utils/testflow/gentool/go.sum
Labels: size/XL, do-not-merge/work-in-progress

#745 listing: fix first page display after new record inserted
  docs/docsrc/examples/examples_admin/activity_test.go
  go.mod
  go.sum
  presets/gorm2op/operator.go
  presets/gorm2op/relay.go
  presets/listing_compo.go
Labels: size/L

#757 Feat daniel ui2
  docs/docsrc/examples/examples_admin/activity_test.go
Labels: size/L, needs-rebase

#700 Support section reload event
  docs/docsrc/examples/examples_presets/detailing_inline_edit.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  presets/section.go
Labels: size/L

#762 feat: adjusting of vx-checkbox default style and add vx-tabs and vx-p…
  example/admin/demo_case.go
  go.mod
  go.sum
  media/filechooser.go
Labels: size/L

#739 publish: support SubqueryConditions and fix tooltips line-break issue
  activity/admin.go
  activity/timeline.go
  docs/docsrc/examples/examples_admin/publish.go
  docs/docsrc/examples/examples_admin/publish_test.go
  example/admin/config.go
  presets/filtering.go
  presets/listing_compo.go
  publish/builder.go
  publish/status_compo.go
Labels: size/L

#752 [Snyk] Security upgrade alpine from 3.16 to 3.20.3
  docs/Dockerfile
Labels: size/XS

#766 [Snyk] Security upgrade alpine from 3.16 to 3.20.3
  example/cmd/data-resetor/Dockerfile
Labels: size/XS

#767 [Snyk] Security upgrade alpine from 3.16 to 3.20.3
  example/Dockerfile
Labels: size/XS

#771 fix: img url is empty
  pagebuilder/example/containers/hero.go
Labels: size/XS

#775 deploy pr774
  cmd/qor5/website-template/admin/config.go
  docs/docsrc/examples/examples_admin/media_allow_types_test.go
  docs/docsrc/examples/examples_admin/media_test.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/publish.go
  example/Dockerfile
  example/admin/config.go
  example/cmd/data-resetor/Dockerfile
  example/integration/media_test.go
  example/models/category.go
  example/models/l10n_model_with_version.go
  example/models/list_model.go
  example/models/post.go
  example/models/product.go
  go.mod
  go.sum
  media/integration/integration_test.go
  media/oss/oss.go
  microsite/builder.go
  microsite/config.go
  microsite/microsite.go
  microsite/utils/client.go
  microsite/utils/utils.go
  pagebuilder/publish.go
  publish/builder.go
  publish/interfaces.go
  publish/list_publish_builder.go
  publish/publish_test.go
  publish/utils.go
Labels: size/L
