Repository qor5/admin, pull requests merged in 2024-06, with the labels that each got.

#248 update module web
  go.mod
  go.sum
  utils/testflow/gentool/go.mod
Labels: size/XS

#250 Fix all tests
  docs/docsrc/examples/examples_admin/activity_test.go
  docs/docsrc/examples/examples_admin/seo_test.go
  example/admin/db.go
  go.mod
  go.sum
  pagebuilder/example/integration_test.go
  utils/testflow/gentool/go.mod
Labels: size/L

#252 update docs Dockerfile and remove old plantbuild
  docs/Dockerfile
  docs/hack/build-app.sh
  docs/hack/build-deploy-app.sh
  docs/hack/get-tools.sh
  docs/hack/update-plantbuild.sh
  docs/hack/verify-plantbuild.sh
  docs/plantbuild/build.jsonnet
  docs/plantbuild/images.jsonnet
  plantbuild/build.jsonnet
  plantbuild/images.jsonnet
Labels: size/L

#254 Remove public and Fix coverage
  .github/workflows/go.yml
  .gitignore
  docs/docsrc/examples/examples_admin/localization_test.go
  docs/public/system/media_libraries/1/file.@qor_preview.png
  docs/public/system/media_libraries/1/file.original.png
  docs/public/system/media_libraries/1/file.png
  example/admin/config.go
  example/admin/user_config.go
  l10n/builder.go
  l10n/config.go
  l10n/events.go
  presets/plugin.go
  publish/list_publish_builder.go
  utils/contains.go
  utils/primary_slugger_where.go
Labels: size/L

#253 fix duplicate;fix some layout
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  docs/docsrc/generated/g1.go
  docs/docsrc/generated/g2.go
  docs/docsrc/generated/g3.go
  example/integration/pagebuilder_test.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/model.go
  pagebuilder/settings.go
Labels: size/XXL

#257 use notification for publish interactions
  docs/docsrc/examples/examples_admin/publish_test/flow_delete_version_test.go
  docs/docsrc/examples/examples_admin/publish_test/flow_duplicate_test.go
  docs/docsrc/examples/examples_admin/publish_test/flow_version_dialog_test.go
  docs/docsrc/examples/examples_admin/publish_test/helper_test.go
  go.mod
  go.sum
  publish/builder.go
  publish/event.go
  publish/helper.go
  publish/interfaces.go
  publish/notification.go
  publish/schedule_event.go
  publish/status_compo.go
  publish/version_compo.go
  publish/version_event.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/XL

#258 Develop
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  go.mod
  go.sum
  pagebuilder/editor.go
  pagebuilder/example/assets/images/BrandGrid.png
  pagebuilder/example/assets/images/BrandGrid.svg
  pagebuilder/example/assets/images/ContactForm.png
  pagebuilder/example/assets/images/ContactForm.svg
  pagebuilder/example/assets/images/Footer.png
  pagebuilder/example/assets/images/Footer.svg
  pagebuilder/example/assets/images/Header.png
  pagebuilder/example/assets/images/Header.svg
  pagebuilder/example/assets/images/Heading.png
  pagebuilder/example/assets/images/Heading.svg
  pagebuilder/example/assets/images/Image.png
  pagebuilder/example/assets/images/Image.svg
  pagebuilder/example/assets/images/InNumbers.png
  pagebuilder/example/assets/images/InNumbers.svg
  pagebuilder/example/assets/images/ListContent.png
  pagebuilder/example/assets/images/ListContent.svg
  pagebuilder/example/assets/images/ListContentLite.png
  pagebuilder/example/assets/images/ListContentLite.svg
  pagebuilder/example/assets/images/ListContentWithImage.png
  pagebuilder/example/assets/images/ListContentWithImage.svg
  pagebuilder/example/assets/images/PageTitle.png
  pagebuilder/example/assets/images/PageTitle.svg
  pagebuilder/example/assets/images/VideoBanner.png
  pagebuilder/example/assets/images/VideoBanner.svg
  pagebuilder/model.go
  pagebuilder/settings.go
Labels: size/L

#256 Move cmd out of docs
  cmd/qor5/admin-template/admin/config.go
  cmd/qor5/admin-template/admin/db.go
  cmd/qor5/admin-template/admin/router.go
  cmd/qor5/admin-template/dev_env
  cmd/qor5/admin-template/docker-compose.yaml
  cmd/qor5/admin-template/main.go
  cmd/qor5/admin-template/models/post.go
  cmd/qor5/bare-template/main.go
  cmd/qor5/main.go
  cmd/qor5/website-template/.gitignore
  cmd/qor5/website-template/admin/config.go
  cmd/qor5/website-template/admin/db.go
  cmd/qor5/website-template/admin/integration_test.go
  cmd/qor5/website-template/admin/messages.go
  cmd/qor5/website-template/admin/qor-logo.png
  cmd/qor5/website-template/admin/router.go
  cmd/qor5/website-template/dev_env
  cmd/qor5/website-template/docker-compose.yaml
  cmd/qor5/website-template/main.go
  dev_env_test
  docker-compose.yaml
  docs/cmd/qor5/website-template/admin/config.go
  docs/cmd/qor5/website-template/admin/db.go
  docs/cmd/qor5/website-template/admin/init_sql.go
  docs/cmd/qor5/website-template/admin/messages.go
  docs/docs/getting-started/one-minute-quick-start.html
  docs/docs/index.js
  docs/docs/search_indexes.json
  docs/docsrc/content/getting-started/one-minute-quick-start.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  docs/docsrc/examples/examples_admin/publish_test/flow_duplicate_test.go
  docs/docsrc/generated/g1.go
  docs/docsrc/generated/g2.go
  docs/docsrc/generated/g3.go
  example/dev.sh
  pagebuilder/builder.go
  pagebuilder/model.go
  presets/integration/fields_test.go
Labels: size/XXL

#260 Upgrade all theplant code to have license
  go.mod
  go.sum
  presets/listing.go
Labels: size/L

#261 feat: section element hover and edit
  presets/section.go
  publish/builder.go
Labels: size/S

#264 Develop
  cmd/qor5/website-template/admin/config.go
  docs/docsrc/generated/g1.go
  docs/docsrc/generated/g2.go
  docs/docsrc/generated/g3.go
  go.mod
  go.sum
  pagebuilder/builder.go
  pagebuilder/content.go
  pagebuilder/editor.go
  pagebuilder/model.go
  pagebuilder/settings.go
  seo/admin.go
Labels: size/XXL

#267 Fix actions permission in listing
  example/integration/perm_test.go
  go.mod
  go.sum
  presets/const.go
  presets/listing.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/L

#268 Develop
  docs/docsrc/examples/examples_presets/filter.go
  go.mod
  go.sum
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/model.go
  seo/admin.go
Labels: size/M

#269 Feat: VersionDialog allow all permission default
  pagebuilder/builder.go
  publish/version_compo.go
Labels: size/S

#270 fix page new dialog;adjust seo layout
  example/integration/pagebuilder_test.go
  example/integration/perm_test.go
  media/integration/integration_test.go
  pagebuilder/builder.go
  pagebuilder/model.go
  seo/admin.go
Labels: size/L

#272 adjust profile
  example/admin/profile.go
  example/integration/profile_test.go
Labels: size/L

#275 Fix/campaign publish
  docs/docs/appendix/all-demo-examples.html
  docs/docs/basics/filter.html
  docs/docs/basics/listing-customizations.html
  docs/docs/basics/presets-instant-crud.html
  docs/docs/basics/publish.html
  docs/docs/search_indexes.json
  docs/docsrc/dev.sh
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  docs/docsrc/generated/g1.go
  docs/docsrc/generated/g2.go
  docs/docsrc/generated/g3.go
  pagebuilder/model.go
  pagebuilder/publish.go
  publish/builder.go
  publish/interfaces.go
  utils/utils.go
Labels: size/XXL

#277 fix PageLayout
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  pagebuilder/builder.go
  pagebuilder/example/config.go
  pagebuilder/page_layout.go
Labels: size/S

#276 feat Add duplicate perm
  presets/const.go
  publish/version_event.go
Labels: size/XS

#278 add warp head and body;fix detail duplicate nothing
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  pagebuilder/builder.go
  pagebuilder/page_layout.go
Labels: size/L

#280 Fix/pagebuilder
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  example/integration/pagebuilder_test.go
  pagebuilder/builder.go
  pagebuilder/models.go
Labels: size/L

#281 fix demo contianers l10n
  example/dev_env
  pagebuilder/builder.go
Labels: size/XS

#284 support NewWithoutAutoMigration
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  pagebuilder/builder.go
Labels: size/M

#285 upgrade qor5/x
  go.mod
  go.sum
Labels: size/S

#283 media list view by uploaded user
  example/admin/config.go
  example/admin/router.go
  example/integration/media_test.go
  example/integration/orders_test.go
  example/integration/pagebuilder_test.go
  example/integration/profile_test.go
  media/builder.go
  media/filechooser.go
  media/media_library/media_library.go
Labels: size/L

#286 change AutoMigrate to Method
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  pagebuilder/builder.go
Labels: size/XS

#287 PageBuilder default not AutoMigrate, Need to specific call it, and Re…
  activity/admin.go
  cmd/qor5/website-template/admin/config.go
  docs/docsrc/content/basics/internationalization.go
  docs/docsrc/examples/examples_admin/internationalization.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_presets/listing.go
  example/admin/config.go
  l10n/builder.go
  login/builder.go
  media/media_box.go
  microsite/config.go
  note/builder.go
  pagebuilder/builder.go
  pagebuilder/example/config.go
  pagebuilder/example/examplemain/main.go
  pagebuilder/example/integration_test.go
  presets/field.go
  presets/integration/fields_test.go
  presets/listeditor.go
  presets/presets.go
  publish/builder.go
  publish/version_compo.go
  seo/admin.go
  slug/field.go
  utils/confirm_dialog.go
  worker/builder.go
Labels: size/L

#288 Support disable media automigrate
  media/builder.go
  media/media_box.go
Labels: size/S

#290 Feat section support i18n, add section label
  presets/detailing.go
  presets/section.go
Labels: size/M

#291 listing: cellWrapperFunc click.self => click
  docs/docsrc/examples/examples_presets/listing.go
  presets/examples/setup.go
  presets/listing.go
  publish/version_compo.go
Labels: size/S
