Repository qor5/admin, pull requests merged in 2024-12, with the labels that each got.

#774 upgrade aws sdk to v2
  cmd/qor5/website-template/admin/config.go
  docs/docsrc/examples/examples_admin/media_allow_types_test.go
  docs/docsrc/examples/examples_admin/media_test.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/publish.go
  example/admin/config.go
  example/admin/router.go
  example/integration/media_test.go
  example/integration/pagebuilder_online_test.go
  example/models/category.go
  example/models/l10n_model_with_version.go
  example/models/list_model.go
  example/models/post.go
  example/models/product.go
  go.mod
  go.sum
  media/integration/integration_test.go
  media/oss/oss.go
  microsite/builder.go
  microsite/config.go
  microsite/microsite.go
  microsite/utils/client.go
  microsite/utils/utils.go
  pagebuilder/publish.go
  pagebuilder/settings.go
  publish/builder.go
  publish/interfaces.go
  publish/list_publish_builder.go
  publish/publish_test.go
  publish/utils.go
Labels: size/L

#787 upgrade imaging
  go.mod
  go.sum
Labels: size/S

#789 Fix kak 6284
  go.mod
  go.sum
Labels: size/S

#794 Fix img url copy
  docs/docsrc/examples/examples_admin/linkage_select_filter_item_remote.go
  media/filechooser.go
  media/messages.go
  media/perm.go
  presets/field.go
Labels: size/M

#799 Fix lax messageshow
  docs/docsrc/examples/examples_admin/media_test.go
  docs/docsrc/examples/examples_presets/editing_test.go
  example/admin/config.go
  example/integration/demo_containers_test.go
  example/integration/page_seo_test.go
  example/integration/pagebuilder_template_test.go
  example/integration/pagebuilder_test.go
  example/integration/post_test.go
  go.mod
  go.sum
  media/filechooser.go
  media/media_box.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/example/containers/image.go
  pagebuilder/model.go
  pagebuilder/model_events.go
  pagebuilder/template.go
  presets/editing.go
  presets/presets.go
  presets/section.go
  seo/admin.go
  seo/admin_test.go
  seo/messages.go
  seo/seo.go
Labels: size/XXL

#798 listing: Fix unexpected behavior caused by unexpected per_page
  go.mod
  go.sum
  presets/gorm2op/operator.go
  presets/gorm2op/relay.go
  presets/listing_compo.go
Labels: size/S

#701 activity: logs filtered by perm && change list header i18n
  activity/activity_log.go
  activity/admin.go
  activity/messages.go
  activity/model_builder.go
  docs/docsrc/examples/examples_admin/activity_test.go
  publish/version_compo.go
Labels: size/L

#804 fix password strength meter space
  login/view_common.go
Labels: size/XS

#806 Fix lax linkage fields
  example/integration/pagebuilder_test.go
  pagebuilder/example/containers/heading.go
  presets/controller.go
  presets/editing.go
  presets/section.go
Labels: size/M

#807 use qor5/imaging v1.6.4
  example/cmd/publisher/Dockerfile
  go.mod
  go.sum
  media/base/handlers.go
  media/base/utils.go
  media/vips/vips.go
Labels: size/M

#805 [Snyk] Security upgrade alpine from 3.16 to 3.21.0
  example/cmd/publisher/Dockerfile
Labels: size/XS

#780 session: add grace period after extend and DisableIPCheck && login: ZxcvbnLogicComponent
  example/admin/auth.go
  example/integration/login_test.go
  example/integration/session_test.go
  go.mod
  go.sum
  login/session.go
  login/views.go
Labels: size/L

#812 feat: replace local CSS file with inline CSS variables for button sty…
  pagebuilder/page_layout.go
Labels: size/M

#815 fix: fixed the page-builder image thumb's width
  go.mod
  go.sum
  media/media_box.go
Labels: needs-rebase, size/M

#816 fix: fixed the page-builder image thumb's width
  go.mod
  go.sum
  media/media_box.go
Labels: size/M

#817 Fix kak 6284
  go.mod
  go.sum
Labels: size/XS, needs-rebase

#821 fix: adjust margin for label in media box and wrap media box in a container
  media/media_box.go
  seo/admin.go
Labels: size/M

#822 fix: adjust margin for label in media box and wrap media box in a container
  media/media_box.go
  seo/admin.go
Labels: size/M

#824 Fix pagination
  docs/docsrc/examples/examples_admin/linkage_select_filter_item_remote.go
  docs/docsrc/examples/examples_admin/media_test.go
  docs/docsrc/examples/examples_admin/publish_test/flow_publish_test.go
  docs/docsrc/examples/examples_presets/perm_role_test.go
  example/integration/media_test.go
  example/integration/pagebuilder_online_test.go
  example/integration/pagebuilder_test.go
  example/integration/post_test.go
  go.mod
  go.sum
  media/cropper.go
  media/filechooser.go
  media/media_box.go
  media/media_library/media_box.go
  media/messages.go
  media/names.go
  media/perm.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/model.go
  pagebuilder/model_events.go
  pagebuilder/template.go
  presets/const.go
  presets/controller.go
  presets/editing.go
  presets/field.go
  presets/field_defaults.go
  presets/integration/fields_test.go
  presets/listener.go
  presets/listing_compo.go
  presets/section.go
  publish/schedule_event.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/XL

#826 feat: Add demo case for vxbtn, vxbtngroup, and vxchip
  example/admin/demo_case.go
  go.mod
  go.sum
Labels: size/XL, needs-rebase

#838 feat: integrate email builder with embedded assets and simplify routing
  emailbuilder/assets.go
  example/admin/router.go
Labels: size/M

#840 Feat daniel democase
  example/admin/demo_case.go
  go.mod
  go.sum
Labels: size/XL, needs-rebase

#825 feat: add democase for vxbtn, vxbtngroup, vxchip
  example/admin/demo_case.go
  go.mod
  go.sum
Labels: size/XL
