Repository qor5/admin, pull requests merged in 2025-03, with the labels that each got.

#897 chore: Update dependencies and Alpine base image version
  docs/Dockerfile
  example/Dockerfile
  example/cmd/data-resetor/Dockerfile
  example/cmd/publisher/Dockerfile
  go.mod
  go.sum
  pagebuilder/model.go
  utils/testflow/gentool/go.sum
Labels: size/M

#901 Fix localize
  example/admin/config.go
  example/integration/pagebuilder_test.go
  l10n/events.go
  pagebuilder/builder.go
  pagebuilder/model.go
Labels: size/M

#899 feat(marketing): introduce tag package for audience segmentation
  .gitignore
  go.mod
  go.sum
  marketing/tag/bg/bigquery.ipynb
  marketing/tag/bg/bigquery_test.go
  marketing/tag/bg/builder.go
  marketing/tag/bg/sql_dialect.go
  marketing/tag/bg/sql_dialect_test.go
  marketing/tag/example_test.go
  marketing/tag/expression.go
  marketing/tag/expression_test.go
  marketing/tag/fragment.go
  marketing/tag/fragment_metadata.go
  marketing/tag/fragment_metadata_test.go
  marketing/tag/hook.go
  marketing/tag/registry.go
  marketing/tag/registry_test.go
  marketing/tag/sql_builder_wrapper.go
  marketing/tag/sql_processor.go
  marketing/tag/sql_processor_test.go
  marketing/tag/sql_template.go
  marketing/tag/sql_template_func.go
  marketing/tag/sql_template_func_test.go
  marketing/tag/sql_template_test.go
  marketing/tag/types.go
  marketing/tag/view.go
  marketing/tag/view_test.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/XXL

#908 refactor: update user segment configuration and improve UI elements
  emailbuilder/dummy_tags.go
  emailbuilder/user_segment.go
  example/admin/config.go
  go.mod
  go.sum
  marketing/tag/bg/builder.go
  marketing/tag/example_test.go
  marketing/tag/fragment_metadata.go
  presets/section.go
Labels: size/L

#919 refactor: update TiptapEditor to use field.FormKey instead of field.Name
  docs/docsrc/examples/examples_presets/editing.go
  example/admin/config.go
  pagebuilder/example/containers/heading.go
  pagebuilder/example/containers/list_content_lite.go
  tiptap/tiptap.go
Labels: size/S

#920 fix: add margin classes to HTML components for improved layout
  presets/listing_compo.go
  presets/section.go
Labels: size/XS

#918 Fix problem by code scan
  docs/Dockerfile
  example/Dockerfile
  example/cmd/data-resetor/Dockerfile
  example/cmd/publisher/Dockerfile
  go.mod
  go.sum
  presets/presets.go
  worker/cron.go
Labels: size/L

#925 fix remove datetimepicker
  example/integration/worker_test.go
  go.mod
  go.sum
  utils/testflow/gentool/go.mod
  worker/job.go
Labels: size/M

#926 use VXSendVariables
  go.mod
  go.sum
  seo/admin.go
  seo/embed.go
  seo/v_seo.go
  seo/v_seo/vue-seo.js
  seo/v_seo/vue-seo.min.js
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/L

#927 Fix datatable func
  docs/docsrc/examples/examples_presets/listing.go
  docs/docsrc/examples/examples_presets/listing_test.go
  docs/docsrc/examples/examples_presets/mux.go
  presets/listing_builder.go
  presets/listing_compo.go
Labels: size/L

#929 fix-qor5-952
  go.mod
  go.sum
Labels: size/XS

#930 Feat share container
  example/integration/demo_containers_test.go
  example/integration/pagebuilder_share_test.go
  example/integration/pagebuilder_test.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/messages.go
  pagebuilder/model.go
  pagebuilder/model_events.go
  pagebuilder/settings.go
  pagebuilder/template.go
  presets/api.go
Labels: size/XL
