Repository qor5/admin, pull requests merged in 2025-05, with the labels that each got.

#965 fix twice create
  presets/editing.go
Labels: size/XS

#964 Feat status disablement
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  publish/builder.go
  publish/version_compo.go
Labels: size/M

#968 refactor: update DataTableFunc to include pagination component
  docs/docsrc/examples/examples_presets/listing.go
  presets/listing_builder.go
  presets/listing_compo.go
Labels: size/M

#970 chore(deps): update github.com/qor5/x/v3 to v3.0.14-0.20250517140108-70e6adb81b7a
  go.mod
  go.sum
Labels: size/XS

#971 Fix remove ps
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/listing.go
  example/integration/demo_containers_test.go
  go.mod
  go.sum
  pagebuilder/builder.go
  pagebuilder/model.go
  pagebuilder/model_events.go
  pagebuilder/page_layout.go
  presets/listing_builder.go
  presets/listing_compo.go
  presets/messages.go
  publish/messages.go
  publish/version_compo.go
Labels: size/L

#963 Fix remove ps
  autocomplete/integration/autocomplete_test.go
  cmd/qor5/website-template/admin/integration_test.go
  docs/docsrc/examples/examples_admin/activity_test.go
  docs/docsrc/examples/examples_admin/autocomplete_test.go
  docs/docsrc/examples/examples_admin/autosync_test.go
  docs/docsrc/examples/examples_admin/linkage_select_filter_item_remote_test.go
  docs/docsrc/examples/examples_admin/listing_test.go
  docs/docsrc/examples/examples_admin/localization_test.go
  docs/docsrc/examples/examples_admin/login_test.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  docs/docsrc/examples/examples_admin/profile_test.go
  docs/docsrc/examples/examples_admin/publish_test.go
  docs/docsrc/examples/examples_admin/redirection_test.go
  docs/docsrc/examples/examples_admin/seo_test.go
  docs/docsrc/examples/examples_admin/singleton_test.go
  docs/docsrc/examples/examples_presets/confirm-dialog_test.go
  docs/docsrc/examples/examples_presets/custom_page_test.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/listing_test.go
  docs/docsrc/examples/examples_presets/presets_test.go
  example/integration/activity_logs_test.go
  example/integration/demo_case_test.go
  example/integration/demo_containers_test.go
  example/integration/list_model_test.go
  example/integration/login_test.go
  example/integration/page_seo_test.go
  example/integration/pagebuilder_online_test.go
  example/integration/pagebuilder_perm_test.go
  example/integration/pagebuilder_share_test.go
  example/integration/pagebuilder_template_test.go
  example/integration/pagebuilder_test.go
  example/integration/profile_test.go
  pagebuilder/builder.go
  pagebuilder/content.go
  pagebuilder/editor.go
  pagebuilder/model.go
  pagebuilder/model_events.go
  pagebuilder/page_layout.go
  pagebuilder/publish_test.go
  pagebuilder/template.go
  pagebuilder/template_events.go
  presets/custom.go
  presets/errors.go
  presets/gorm2op/operator.go
  presets/integration/fields_test.go
  presets/messages.go
  presets/presets.go
  publish/messages.go
  publish/version_compo.go
Labels: size/XXL

#973 chore(deps): update github.com/qor5/x/v3 to v3.0.14-0.20250523072426-…
  go.mod
  go.sum
Labels: size/XS

#975 chore(docker): update base image to golang:1.23-alpine in all Dockerfiles
  docs/Dockerfile
  example/Dockerfile
  example/cmd/data-resetor/Dockerfile
  example/cmd/publisher/Dockerfile
Labels: size/XS
