Repository qor5/admin, pull requests merged in 2025-01, with the labels that each got.

#846 Fix crop
  media/README.md
  media/base/base.go
  media/base/handlers.go
  media/cropper.go
  media/filechooser.go
  media/integration/integration_test.go
  media/media_library/media_box.go
  media/media_library/media_library.go
Labels: size/L

#851 Fix tab controller
  docs/docsrc/examples/examples_presets/mux.go
  docs/docsrc/examples/examples_presets/tab_controller.go
  docs/docsrc/examples/examples_presets/tab_controller_test.go
  presets/controller.go
  presets/field.go
  presets/integration/fields_test.go
Labels: size/L

#828 activity: add SkipResPermCheck
  activity/admin.go
  activity/builder.go
  docs/docsrc/examples/examples_admin/activity_test.go
Labels: size/L

#852 Fix crop
  example/integration/pagebuilder_test.go
  go.mod
  go.sum
  media/README.md
  media/base/base.go
  media/base/handlers.go
  media/base/upload.go
  media/base/utils.go
  media/cropper.go
  media/events.go
  media/filechooser.go
  media/integration/integration_test.go
  media/media_box.go
  media/media_library/media_box.go
  media/media_library/media_library.go
  media/perm.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/model.go
  pagebuilder/model_events.go
  publish/schedule_event.go
Labels: size/XL

#854 change visible v-if to v-show
  presets/field.go
  presets/integration/fields_test.go
Labels: size/L

#856 fix: comment out the replace directive for qor5/x module in go.mod
  go.mod
Labels: size/XS

#860 [Snyk] Security upgrade alpine from 3.20.3 to 3.21.2
  docs/Dockerfile
Labels: size/XS

#859 [Snyk] Security upgrade alpine from 3.20.3 to 3.21.2
  example/cmd/data-resetor/Dockerfile
Labels: size/XS

#858 [Snyk] Security upgrade alpine from 3.20.3 to 3.21.2
  example/Dockerfile
  example/cmd/publisher/Dockerfile
Labels: size/XS

#863 update github.com/qor5/x/v3 to v3.0.14-0.20250116084234-2b32130b3d69
  docs/Dockerfile
  example/Dockerfile
  example/cmd/data-resetor/Dockerfile
  example/cmd/publisher/Dockerfile
  go.mod
  go.sum
Labels: size/S, needs-rebase

#866 AutoMigrate
  example/admin/config.go
Labels: size/XS

#870 upgrade x
  go.mod
  go.sum
Labels: size/XS

#871 Fix daniel qor5 706
  example/Dockerfile
  example/cmd/publisher/Dockerfile
  go.mod
  go.sum
Labels: size/S, needs-rebase
