Repository qor5/admin, pull requests merged in 2025-04, with the labels that each got.

#934 Fix online edit
  example/integration/pagebuilder_online_test.go
  presets/integration/section_test.go
  presets/section.go
  publish/builder.go
  publish/event.go
  publish/messages.go
  publish/version_compo.go
  publish/version_event.go
Labels: size/L

#936 change mode to VIEW_MODE_FIT_WITHIN_CONTAINER
  example/integration/media_test.go
  media/cropper.go
Labels: size/S

#937 fix vue debug warning
  login/profile.go
  pagebuilder/editor.go
  pagebuilder/model_events.go
  presets/const.go
  presets/listing_compo.go
  publish/status_compo.go
  publish/version_compo.go
Labels: size/M

#938 Feat daniel plain field body
  docs/docsrc/examples/examples_presets/mux.go
  docs/docsrc/examples/examples_presets/presets_plain_nested_field.go
  docs/docsrc/examples/examples_presets/presets_plain_nested_field_test.go
  presets/field.go
  presets/integration/fields_test.go
Labels: size/L

#939 add section disabled save
  docs/docsrc/examples/examples_presets/detailing.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/mux.go
  presets/editing.go
  presets/section.go
Labels: size/M

#940 refactor: simplify error handling in SelectField function
  presets/field_defaults.go
Labels: size/XS

#941 chore: update dependency version for github.com/qor5/x/v3 to v3.0.14-0.20250410095219-660fa766259c
  go.mod
  go.sum
Labels: size/S

#943 chore: update dependency version for github.com/qor5/x/v3 to v3.0.14-0.20250414083701-4bdbf32e86c4
  go.mod
  go.sum
Labels: size/XS

#942 Fix container data
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  example/integration/pagebuilder_share_test.go
  pagebuilder/builder.go
  pagebuilder/model_events.go
Labels: size/M

#945 Fix wrap publish
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  pagebuilder/builder.go
Labels: size/L

#861 login: add WithValidateSessionHook
  common/hook.go
  common/hook_test.go
  example/integration/session_test.go
  login/session.go
Labels: size/L

#933 feat: introduce error handling for panic
  docs/docsrc/examples/examples_admin/localization.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/publish.go
  example/integration/pagebuilder_template_test.go
  example/integration/pagebuilder_test.go
  example/models/category.go
  example/models/l10n_model.go
  example/models/l10n_model_with_version.go
  example/models/list_model.go
  example/models/post.go
  example/models/product.go
  microsite/microsite.go
  pagebuilder/models.go
  presets/errors.go
  presets/integration/gorm_operator_test.go
  presets/presets.go
  seo/model.go
Labels: size/L

#935 login: add WithSessionTableHook
  example/admin/auth.go
  example/integration/profile_test.go
  login/session.go
Labels: size/M

#947 feat: implement not found handler and improve error handling
  example/integration/pagebuilder_test.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  presets/errors.go
  presets/presets.go
Labels: size/M

#948 Mostly small bug fixes
  login/profile.go
  media/base/base.go
  publish/builder.go
  publish/constant.go
  publish/utils.go
  worker/builder.go
Labels: size/M

#949 fix preview seo host schema
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  pagebuilder/model.go
  publish/builder.go
  publish/interfaces.go
  seo/builder.go
Labels: size/S

#951 fix CtxKeyDB
  presets/gorm2op/operator.go
Labels: size/XS

#954 Fix locale
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  example/integration/pagebuilder_locale_test.go
  example/integration/pagebuilder_share_test.go
  example/integration/pagebuilder_test.go
  l10n/builder.go
  l10n/config.go
  l10n/events.go
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/model.go
  pagebuilder/page.go
  pagebuilder/settings.go
  presets/presets.go
  publish/builder.go
  publish/interfaces.go
  publish/version_compo.go
  seo/builder.go
Labels: size/L

#956 refactor: use sync.Once for modelMap initialization in MenuOrderBuilder
  presets/menu_order.go
Labels: size/S

#957 feat: add campaign with string ID version list dialog test and enhanc…
  docs/docsrc/examples/examples_admin/page_builder_with_campaign.go
  docs/docsrc/examples/examples_admin/page_builder_with_campaign_test.go
  publish/builder.go
  publish/version_compo.go
Labels: size/M
