Repository qor5/admin, pull requests merged in 2025-02, with the labels that each got.

#875 fix Click container twice will add two same container
  pagebuilder/model_events.go
Labels: size/S

#868 WIP: test: update qor5/x/v3 dependency version in go.mod and go.sum
  go.mod
  go.sum
Labels: size/S, do-not-merge/work-in-progress

#876 fix redirection docs
  docs/docs/basics/redirection.html
  docs/docs/search_indexes.json
  docs/docsrc/content/basics/redirection.go
  docs/docsrc/examples/examples_admin/redirection.go
  docs/docsrc/generated/g2.go
  docs/docsrc/generated/g3.go
Labels: size/M

#878 fix no group add; add renderContainerHover generate Hover Container …
  pagebuilder/model_events.go
Labels: size/M

#887 Fix switch locale
  example/admin/config.go
  example/integration/page_location_test.go
  example/integration/profile_test.go
  go.mod
  go.sum
  l10n/builder.go
  l10n/config.go
  login/profile.go
  presets/integration/language_test.go
  presets/presets.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/L

#890 Exporting presets.NewMenuOrderBuilder to allow custom layouts to bene…
  presets/menu_order.go
  presets/presets.go
Labels: size/XS
