Repository qor5/admin, pull requests merged in 2025-06, with the labels that each got.

#984 Fix iframe event
  go.mod
  go.sum
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/example/containers/in_numbers.go
  pagebuilder/model_events.go
Labels: size/M

#987 feat: add pauseVideo parameter to iframe URL in overview function
  pagebuilder/settings.go
Labels: size/S

#1003 refactor: update newReloadAction to accept parameters for improved ke…
  presets/listing_compo.go
Labels: size/S

#996 https://theplanttokyo.atlassian.net/browse/QOR5-984
  docs/docsrc/examples/examples_admin/localization.go
  docs/docsrc/examples/examples_admin/localization_test.go
  docs/docsrc/examples/examples_admin/profile_language_simple_test.go
  example/admin/config.go
  example/integration/demo_containers_test.go
  example/integration/media_test.go
  example/integration/page_location_test.go
  example/integration/page_seo_test.go
  example/integration/pagebuilder_locale_test.go
  example/integration/pagebuilder_online_test.go
  example/integration/pagebuilder_perm_test.go
  example/integration/pagebuilder_share_test.go
  example/integration/pagebuilder_template_test.go
  example/integration/pagebuilder_test.go
  go.mod
  go.sum
  login/profile.go
  pagebuilder/builder.go
  pagebuilder/editor.go
Labels: size/XL

#995 feat: add class management to TiptapEditorBuilder
  docs/docsrc/examples/examples_admin/tiptap_test.go
  go.mod
  go.sum
  tiptap/tiptap.go
Labels: size/L

#972 Feat seo view
  docs/docsrc/examples/examples_admin/seo_test.go
  seo/admin.go
  seo/messages.go
Labels: size/L

#1001 Update dependencies in go.mod and go.sum; enhance pagebuilder with ne…
  pagebuilder/builder.go
  pagebuilder/editor.go
  pagebuilder/messages.go
Labels: size/M

#994 Fix last draft
  example/integration/pagebuilder_online_test.go
  pagebuilder/builder.go
  pagebuilder/messages.go
  pagebuilder/model.go
Labels: size/L

#998 Feat breadcrumb
  docs/docsrc/examples/examples_admin/activity_test.go
  pagebuilder/page.go
  presets/detailing.go
  presets/messages.go
  presets/model.go
  presets/presets.go
Labels: size/L

#1007 fix param
  presets/detailing.go
  utils/testflow/gentool/go.mod
  utils/testflow/gentool/go.sum
Labels: size/XS

#1008 Feat wrap side panel
  docs/docsrc/examples/examples_presets/detailing.go
  docs/docsrc/examples/examples_presets/detailing_test.go
  docs/docsrc/examples/examples_presets/mux.go
  go.mod
  go.sum
  presets/detailing.go
  presets/listing_compo.go
Labels: size/L

#999 Fix filter
  activity/admin.go
  docs/docsrc/examples/examples_vuetifyx/filter-demo.go
  docs/docsrc/examples/examples_vuetifyx/filter-demo_test.go
  example/admin/config.go
  example/admin/order_config.go
  example/admin/user_config.go
  go.mod
  go.sum
Labels: size/L

#1006 https://theplanttokyo.atlassian.net/browse/QOR5-1329
  docs/docsrc/examples/examples_admin/field_listeditor_example.go
  docs/docsrc/examples/examples_admin/field_listeditor_test.go
  docs/docsrc/examples/examples_admin/mux.go
  presets/field.go
  presets/listeditor.go
  presets/messages.go
Labels: size/L

#1013 Add handler hook support to Builder and implement NewMuxHook method
  activity/timeline.go
  presets/presets.go
  presets/presets_test.go
Labels: size/L
